;;;; test/desk-test.lisp — glass/desk: windows, the root menu, dragging, damage, the keyboard hook.
;;;;   sbcl --non-interactive --load test/desk-test.lisp     (exits 0 iff every check passes)

(load (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname)))
(push (make-pathname :name nil :type nil
                     :defaults (merge-pathnames "../" (make-pathname :name nil :type nil
                                                                     :defaults *load-truename*)))
      asdf:*central-registry*)
(handler-bind ((warning #'muffle-warning))
  (let ((*standard-output* (make-broadcast-stream))) (asdf:load-system :glass/desk)))

(defpackage #:glass-desk-test (:use #:cl))
(in-package #:glass-desk-test)

(defvar *fails* 0)
(defvar *got* nil)
(defun check (name ok)
  (format t "~&DESK ~:[FAIL~;ok  ~] ~a~%" ok name)
  (unless ok (incf *fails*)))

(defun win-x (w) (glass.desk::win-x w))
(defun win-y (w) (glass.desk::win-y w))

;; windows, the menu, dragging, input, closing
(let* ((screen (glass:make-framebuffer 600 800))
       (d (glass.desk:make-desk screen)))
  (glass.desk:desk-register-app d "Red" (lambda (fb) (glass:fb-fill fb #xff0000)
                                            (values nil (lambda (m x y) (push (list m x y) *got*))
                                                    (lambda () nil)))
                                :width 200 :height 150)
  (check "first tick draws" (glass.desk:desk-tick d))
  (check "idle tick does not" (not (glass.desk:desk-tick d)))
  (glass.desk:desk-pointer d 1 300 400) (glass.desk:desk-pointer d 0 300 400)
  (glass.desk:desk-tick d)
  (check "background tap opens menu" (/= (glass:fb-get screen 310 410) #x1e2530))
  (glass.desk:desk-pointer d 1 310 410) (glass.desk:desk-pointer d 0 310 410)
  (glass.desk:desk-tick d)
  (let ((w (first (glass.desk:desk-windows d))))
    (check "menu item opens window" w)
    (check "window content on screen" (= (glass:fb-get screen (+ (win-x w) 5) (+ (win-y w) 5)) #xff0000))
    (let ((x0 (win-x w)) (y0 (win-y w)))
      (glass.desk:desk-pointer d 1 (+ x0 20) (- y0 10))
      (glass.desk:desk-pointer d 1 (+ x0 120) (+ y0 90))
      (glass.desk:desk-pointer d 0 (+ x0 120) (+ y0 90))
      (glass.desk:desk-tick d)
      (check "drag moved window" (and (= (win-x w) (+ x0 100)) (= (win-y w) (+ y0 100))))
      (check "content at new place" (= (glass:fb-get screen (+ x0 105) (+ y0 105)) #xff0000))
      (glass.desk:desk-pointer d 1 (+ x0 110) (+ y0 107)) (glass.desk:desk-pointer d 0 (+ x0 110) (+ y0 107))
      (check "content gets local pointer" (equal (second *got*) '(1 10 7)))
      (multiple-value-bind (fx fy fw) (glass.desk::%frame-box w)
        (glass.desk:desk-pointer d 1 (+ fx fw -5) (+ fy 5)))
      (glass.desk:desk-tick d)
      (check "close box closes" (null (glass.desk:desk-windows d))))))

;; a window can't be dragged out of reach
(let* ((screen (glass:make-framebuffer 400 400)) (d (glass.desk:make-desk screen)))
  (glass.desk:desk-register-app d "A" (lambda (fb) (declare (ignore fb)) (values nil nil (lambda () nil)))
                                :width 100 :height 80)
  (let ((w (glass.desk:desk-open d "A")))
    (glass.desk:desk-pointer d 1 (+ (win-x w) 10) (- (win-y w) 10))
    (glass.desk:desk-pointer d 1 5000 5000) (glass.desk:desk-pointer d 0 5000 5000)
    (check "drag keeps the title bar on screen" (and (<= (win-x w) 360) (<= (win-y w) 396)))))

;; region scaling = whole scaling, inside the region
(let* ((src (glass:make-framebuffer 37 23)) (a (glass:make-framebuffer 74 46)) (b (glass:make-framebuffer 74 46)))
  (dotimes (i (* 37 23)) (setf (aref (glass:fb-pixels src) i) (random #xffffff)))
  (glass:fb-blit-scaled a src 0 0 2)
  (glass:fb-blit-scaled-region b src 2 5 3 20 11)
  (check "region scale matches inside, untouched outside"
         (loop for y below 46 always
               (loop for x below 74 always
                     (if (and (<= 10 x) (< x 50) (<= 6 y) (< y 28))
                         (= (glass:fb-get a x y) (glass:fb-get b x y))
                         (= 0 (glass:fb-get b x y)))))))

;; damage: a content-only change reports just the window
(let* ((screen (glass:make-framebuffer 600 800)) (d (glass.desk:make-desk screen)) (flag nil))
  (glass.desk:desk-register-app d "A" (lambda (fb) (values nil nil (lambda () (when flag (setf flag nil) (glass:fb-fill fb #x00ff00) t))))
                                :width 100 :height 80)
  (glass.desk:desk-open d "A") (glass.desk:desk-tick d)
  (setf flag t)
  (let ((w (first (glass.desk:desk-windows d))))
    (multiple-value-bind (ch x y ww hh) (glass.desk:desk-tick d)
      (check "content change reports only the window"
             (and ch (= x (win-x w)) (= y (win-y w)) (= ww 100) (= hh 80)))
      (check "and drew it" (= (glass:fb-get screen (+ x 1) (+ y 1)) #x00ff00)))))

;; damage repaint == full repaint, after drags / raise / menu
(let* ((screen (glass:make-framebuffer 400 500)) (d (glass.desk:make-desk screen)) (ok t))
  (glass.desk:desk-register-app d "A" (lambda (fb) (glass:fb-fill fb #xaa0000) (values nil nil (lambda () nil))) :width 150 :height 100)
  (glass.desk:desk-register-app d "B" (lambda (fb) (glass:fb-fill fb #x00aa00) (values nil nil (lambda () nil))) :width 120 :height 140)
  (setf (glass.desk:desk-keyboard-fn d) (lambda () nil))      ; draw the keys buttons too
  (glass.desk:desk-open d "A") (glass.desk:desk-open d "B") (glass.desk:desk-tick d)
  (flet ((same-as-full ()
           (glass.desk:desk-tick d)
           (let ((partial (copy-seq (glass:fb-pixels screen))))
             (glass.desk:desk-redraw d) (glass.desk:desk-tick d)
             (equalp partial (glass:fb-pixels screen)))))
    (let ((a (second (glass.desk:desk-windows d))))
      (glass.desk:desk-pointer d 1 (+ (win-x a) 10) (- (win-y a) 10))
      (dotimes (i 6)
        (glass.desk:desk-pointer d 1 (+ (win-x a) 10 17) (+ (win-y a) 3))
        (unless (same-as-full) (setf ok nil)))
      (glass.desk:desk-pointer d 0 (+ (win-x a) 10) (- (win-y a) 10))
      (unless (same-as-full) (setf ok nil))
      (glass.desk:desk-pointer d 1 350 450) (glass.desk:desk-pointer d 0 350 450)
      (unless (same-as-full) (setf ok nil))
      (glass.desk:desk-pointer d 1 5 5) (glass.desk:desk-pointer d 0 5 5)
      (unless (same-as-full) (setf ok nil))))
  (check "damage repaint equals full repaint" ok))

;; the keys button toggles the host keyboard and raises its window; keys reach the top window
(let* ((screen (glass:make-framebuffer 600 800)) (d (glass.desk:make-desk screen)) (toggled 0) (keys nil))
  (setf (glass.desk:desk-keyboard-fn d) (lambda () (incf toggled)))
  (glass.desk:desk-register-app d "K" (lambda (fb) (declare (ignore fb))
                                        (values (lambda (down ks) (when down (push ks keys))) nil (lambda () nil)))
                                :width 200 :height 100)
  (glass.desk:desk-register-app d "L" (lambda (fb) (declare (ignore fb)) (values nil nil (lambda () nil)))
                                :width 200 :height 100)
  (let ((k (glass.desk:desk-open d "K")))
    (glass.desk:desk-open d "L") (glass.desk:desk-tick d)
    (multiple-value-bind (fx fy fw) (glass.desk::%frame-box k)
      (glass.desk:desk-pointer d 1 (+ fx fw -30) (+ fy 5)) (glass.desk:desk-pointer d 0 (+ fx fw -30) (+ fy 5)))
    (check "keys button toggles keyboard" (= toggled 1))
    (check "keys button raises its window" (eq k (first (glass.desk:desk-windows d))))
    (glass.desk:desk-key d t #x61) (glass.desk:desk-key d nil #x61)
    (check "key reaches top window" (equal keys '(#x61)))))

(format t "~&DESK ~:[FAIL (~d)~;PASS~]~%" (zerop *fails*) *fails*)
(sb-ext:exit :code (if (zerop *fails*) 0 1))
