;;;; encode-profile.lisp — where does a heavy frame's CPU go?  In-process (no
;;;; sockets/threads), so host load doesn't skew it.  Simulate a terminal-sized
;;;; region changing every frame and time the RFB sender's stages: diff (find
;;;; dirty tiles) / ZRLE-encode / snapshot-update.
;;;;   sbcl --non-interactive --load backend/inspect/encode-profile.lisp
(require :asdf)
(load "~/quicklisp/setup.lisp")
(handler-bind ((warning #'muffle-warning))
  (let ((*standard-output* (make-broadcast-stream))) (ql:quickload '(:glass :cram))))
(in-package :glass)

;; a binary sink that just counts bytes (stands in for the socket)
(defclass sink (sb-gray:fundamental-binary-output-stream) ((n :initform 0 :accessor sink-n)))
(defmethod sb-gray:stream-write-byte ((s sink) b) (incf (sink-n s)) b)
(defmethod sb-gray:stream-write-sequence ((s sink) seq &optional (start 0) end)
  (incf (sink-n s) (- (or end (length seq)) start)) seq)
(defmethod sb-gray:stream-force-output ((s sink)) nil)

(defun ms (a b) (/ (* 1000.0 (- b a)) internal-time-units-per-second))

(let* ((w 1280) (h 800) (fb (make-framebuffer w h)) (px (fb-pixels fb))
       (snap (make-array (* w h) :element-type '(unsigned-byte 32)))
       ;; a terminal-sized dirty region (like a scrolling 90x26 term)
       (rx 40) (ry 62) (rw 720) (rh 442) (region (list rx ry (+ rx rw) (+ ry rh)))
       (zs (cram:make-zstream)) (s (make-instance 'sink))
       (iters 40) (seed 12345)
       (tdiff 0) (tenc 0) (tsnap 0) (nrects 0) (nbytes 0))
  (dotimes (y h) (dotimes (x w) (setf (aref px (+ (* y w) x)) (logior (ash (mod x 256) 16) (ash (mod y 256) 8) 30))))
  (replace snap px)
  (dotimes (i iters)
    ;; churn the region (deterministic pseudo-random, like new terminal text)
    (dotimes (yy rh) (dotimes (xx rw)
      (setf seed (logand (+ (* seed 1103515245) 12345) #xffffffff))
      (setf (aref px (+ (* (+ ry yy) w) (+ rx xx))) (logand seed #xffffff))))
    (let* ((a (get-internal-real-time))
           (rects (dirty-rects fb snap region))
           (b (get-internal-real-time)))
      (setf (sink-n s) 0)
      (dolist (r rects) (destructuring-bind (x y ww hh) r (write-rect-zrle s fb x y ww hh zs)))
      (let ((c (get-internal-real-time)))
        (update-snapshot fb snap rects)
        (let ((d (get-internal-real-time)))
          (incf tdiff (- b a)) (incf tenc (- c b)) (incf tsnap (- d c))
          (setf nrects (length rects) nbytes (sink-n s))))))
  ;; TRLE cost = pack only, NO deflate (the whole region as one rect)
  (let ((tpack 0) (plen 0))
    (dotimes (i iters)
      (dotimes (yy rh) (dotimes (xx rw)
        (setf seed (logand (+ (* seed 1103515245) 12345) #xffffffff))
        (setf (aref px (+ (* (+ ry yy) w) (+ rx xx))) (logand seed #xffffff))))
      (let ((a (get-internal-real-time)))
        (multiple-value-bind (buf len) (pack-rect fb rx ry rw rh) (declare (ignore buf))
          (incf tpack (- (get-internal-real-time) a)) (setf plen len))))
    (format t "~&region ~dx~d (~d px), ~d iters, avg per frame:~%" rw rh (* rw rh) iters)
    (format t "  diff (dirty-rects):   ~,2f ms~%" (ms 0 (/ tdiff iters)))
    (format t "  encode (ZRLE):        ~,2f ms  (~d rects, ~,1f KB)~%" (ms 0 (/ tenc iters)) nrects (/ nbytes 1024.0))
    (format t "  TRLE pack (no zlib):  ~,2f ms  (~,1f KB, single-thread)~%" (ms 0 (/ tpack iters)) (/ plen 1024.0)))
  (format t "  snapshot update:      ~,2f ms~%" (ms 0 (/ tsnap iters)))
  (format t "  TOTAL sender/frame:   ~,2f ms  (~,1f fps ceiling from this alone)~%"
          (ms 0 (/ (+ tdiff tenc tsnap) iters))
          (/ (* iters internal-time-units-per-second) (+ tdiff tenc tsnap))))
(finish-output) (sb-ext:exit)
