;;;; nostr-gate.lisp — the identity, the store, the commands, and the service on a real socket.
;;;;
;;;;   sbcl --non-interactive --load inspect/nostr-gate.lisp
;;;;
;;;; src/nostr.lisp moved the enrolment store, the token mint and the DM command surface out of a
;;;; WebRTC gateway and into the desktop.  Three claims come with that move and all three are
;;;; checkable without a relay, without a gateway and without a phone:
;;;;
;;;;   1. A TOKEN MINTED BY THE OLD IMPLEMENTATION STILL VERIFIES.  Every magic link in somebody's
;;;;      message history is a string in the old format keyed by the old MAC, so this is not a
;;;;      nicety — it is whether the day this deploys is the day every issued link stops working.
;;;;      The check is a LITERAL token, minted by demo/glass-webrtc/login-token.lisp against a
;;;;      literal secret, frozen here.  A literal rather than a call, so it survives that file
;;;;      being deleted and cannot be quietly regenerated by the thing it is testing.
;;;;
;;;;   2. `devices' AND `revoke' ARE ALLOWLIST-ONLY.  A device key is a bearer credential that can
;;;;      be lifted out of a browser; it may ask for a link and nothing else.  If it could revoke,
;;;;      one stolen browser key could lock the owner out of their own desktop, and if it could
;;;;      list, it could enumerate the fleet.  Both are asserted from the device's side.
;;;;
;;;;   3. THE SERVICE IS THE PROTOCOL, not a function call dressed up as one.  Everything below the
;;;;      "over a real socket" banner goes through TCP on loopback, parses the reply text, and
;;;;      exercises the case the gateway's failure policy is built on: a service that is NOT THERE
;;;;      must answer :UNREACHABLE and never NIL-that-looks-like-a-denial.
;;;;
;;;; NOTHING HERE READS OR WRITES THE LIVE ENROLMENT FILE.  A suite that pointed at it would revoke
;;;; a real terminal to pass, which has happened on this box before.  The fixture is in /tmp, it is
;;;; bound before anything is called, and there is an assertion that it is.

(require :asdf)
(load "~/quicklisp/setup.lisp")
(handler-bind ((warning #'muffle-warning))
  (let ((*standard-output* (make-broadcast-stream)))
    (asdf:load-system :glass/nostr)))

(defpackage #:glass-nostr-gate (:use #:cl)) (in-package #:glass-nostr-gate)

(defvar *pass* 0) (defvar *fail* 0)
(defun ok (name p &optional detail)
  (if p (progn (incf *pass*) (format t "  ok   ~a~@[ — ~a~]~%" name detail))
      (progn (incf *fail*) (format t "  FAIL ~a~@[ — ~a~]~%" name detail)))
  (finish-output))
(defun banner (s) (format t "~&~%== ~a ==~%" s))

;;; ---- the fixture, in /tmp, and never anywhere else ---------------------------

(defparameter *fixture* "/tmp/glass-nostr-gate-devices")
(defparameter *live*
  ;; THE REAL LIVE STORE: wherever GLASS:*ENROLMENT-FILE* defaults to — $GLASS_DEVICE_FILE,
  ;; else ~/.glass-devices.
  ;;
  ;; It used to name /home/claude/webrtc-data/demo/glass-webrtc/.glass-devices: one
  ;; machine's home directory, one repository ago.  Everything below asserts that this
  ;; gate does NOT touch the live store — and against a path that exists nowhere,
  ;; PROBE-FILE is NIL, the mtime comparison is NIL against NIL, and every one of those
  ;; checks passes without testing anything.  A safety check aimed at a file that cannot
  ;; exist is the most comfortable kind of green there is.
  (or (sb-ext:posix-getenv "GLASS_DEVICE_FILE")
      (namestring (merge-pathnames ".glass-devices" (user-homedir-pathname)))))

(defparameter *owner* "1111111111111111111111111111111111111111111111111111111111111111")
(defparameter *guest* "2222222222222222222222222222222222222222222222222222222222222222")
(defparameter *rando* "3333333333333333333333333333333333333333333333333333333333333333")

(defparameter *secret* "00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff")

(ignore-errors (delete-file *fixture*))
(setf glass:*enrolment-file* *fixture*
      glass::*enrolments-mtime* nil
      glass:*box-secret* *secret*
      glass:*login-url-base* "https://example.invalid/k1.html")
(glass:refresh-nostr-allow *owner*)
(clrhash glass:*enrolments*)
;; the login-code store rides on the enrolment file's path, so redirecting one redirects both —
;; but a suite that assumed that and was wrong would write the LIVE store, so it is asserted below
;; rather than trusted, and the file is cleared here the same way the enrolments are.
(ignore-errors (delete-file (glass:login-code-file)))
(setf glass:*login-codes* (make-instance 'glass:login-code-store))

(defun hexkey (n) (string-downcase (format nil "~64,'0x" n)))   ; a pubkey-shaped string per N

(defun namedkey (prefix)
  "A pubkey-shaped string that STARTS with PREFIX, so its first eight characters identify it.
HEXKEY pads on the LEFT, which makes every key it produces start with zeros — fine until a test
revokes by an 8-character prefix, at which point `00000000' matches the whole fleet.  (It did.)"
  (string-downcase (concatenate 'string prefix
                                (make-string (- 64 (length prefix)) :initial-element #\0))))

(defun slurp (path)
  "PATH's whole text, or \"\" if it is not there.  The code store is asserted against its FILE and
not only against the process's memory, because the file is the half that survives a restart."
  (with-open-file (s path :if-does-not-exist nil)
    (if (null s) ""
        (with-output-to-string (o)
          (loop for l = (read-line s nil) while l do (write-line l o))))))

(banner "the fixture is in /tmp and the live store is not touched")
(ok "the enrolment file is under /tmp" (eql 0 (search "/tmp/" glass:*enrolment-file*)))
(ok "and it is not the live one" (not (equal glass:*enrolment-file* *live*)))
(ok "the login-code store is DERIVED from it, so one redirection moves both"
    (and (equal (glass:login-code-file) (concatenate 'string *fixture* ".codes"))
         (eql 0 (search "/tmp/" (glass:login-code-file))))
    (glass:login-code-file))
(let ((before (and (probe-file *live*) (file-write-date *live*))))
  (defparameter *live-mtime-before* before)
  (ok "the live store's mtime is noted, and checked again at the end"
      (or (null before) (integerp before))))
(defparameter *live-codes* (concatenate 'string *live* ".codes"))
(defparameter *live-codes-before* (and (probe-file *live-codes*) (file-write-date *live-codes*)))

;;; ==============================================================================
(banner "the identity")
;;; ==============================================================================

(ok "a 64-hex secret is an identity" (glass:box-identity-p))
(ok "and it has a pubkey" (let ((p (glass:box-pubkey))) (and (stringp p) (= 64 (length p)))))
(ok "and an npub, which is its public name"
    (let ((n (glass:box-npub))) (and (stringp n) (eql 0 (search "npub1" n)))))
(let ((glass:*box-secret* nil))
  (ok "no secret is no identity — and that is a refusal, not a fallback"
      (and (not (glass:box-identity-p)) (null (glass:box-pubkey))))
  (ok "…so nothing can be minted with it" (null (glass:mint-login-token))))
(let ((glass:*box-secret* "nope"))
  (ok "and neither is a short one" (not (glass:box-identity-p))))

;;; ==============================================================================
(banner "login tokens — the format is frozen, and this is the proof")
;;; ==============================================================================

;; MINTED BY THE PREVIOUS IMPLEMENTATION (demo/glass-webrtc/login-token.lisp, GLASS-LOGIN:%MAC)
;; against *SECRET*, with a nonce and an expiry chosen so the literal never goes stale:
;;     nonce 0123456789abcdef0123456789abcdef   exp 4102444800 (2100-01-01)
;; If this line ever has to be regenerated, every login link ever issued has already broken.
(defparameter *old-token*
  "0123456789abcdef0123456789abcdef.4102444800.733c4bc58fcd558359520d9e673f2d072755cdfeed281415016418bbbac44638")

(multiple-value-bind (ok-p nonce exp) (glass:verify-login-token *old-token*)
  (ok "a token minted by the OLD code verifies under the new one" ok-p)
  (ok "  …with the same nonce" (equal nonce "0123456789abcdef0123456789abcdef"))
  (ok "  …and the same expiry" (eql exp 4102444800)))
(ok "and it is :OK, not merely parseable" (eq :ok (glass:login-token-status *old-token*)))

(let ((fresh (glass:mint-login-token :ttl 900)))
  (ok "a freshly minted token verifies" (glass:verify-login-token fresh))
  (ok "it has the same three-field shape the browser and the link minter parse"
      (and (= 2 (count #\. fresh))
           (let* ((d1 (position #\. fresh)) (d2 (position #\. fresh :from-end t)))
             (and (= 32 d1) (parse-integer (subseq fresh (1+ d1) d2))
                  (= 64 (- (length fresh) d2 1))))))
  (ok "two mints differ — the nonce is random, so a link is not a constant"
      (not (equal fresh (glass:mint-login-token :ttl 900))))
  (ok "a token from another box's secret does NOT verify here"
      (not (glass:verify-login-token
            (glass:mint-login-token :ttl 900 :secret (make-string 64 :initial-element #\a)))))
  (ok "a flipped MAC character is refused"
      (let ((bad (copy-seq fresh)))
        (setf (char bad (1- (length bad))) (if (char= #\a (char bad (1- (length bad)))) #\b #\a))
        (not (glass:verify-login-token bad))))
  (ok "and garbage is :BAD rather than an error" (eq :bad (glass:login-token-status "not-a-token")))
  (ok "an absent code is :ABSENT, which is a different denial"
      (and (eq :absent (glass:login-token-status nil))
           (eq :absent (glass:login-token-status "")))))

;; expiry is checked, and reported as its own reason so a denial is diagnosable
(let ((expired (let ((n "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") (e (- (glass:unix-now) 60)))
                 (format nil "~a.~a.~a" n e (glass::%token-mac *secret* n e)))))
  (ok "a good MAC on a past expiry is :EXPIRED, not :BAD"
      (eq :expired (glass:login-token-status expired)))
  (ok "  …and VERIFY still hands back the nonce, which is what tells the two apart"
      (multiple-value-bind (ok-p nonce) (glass:verify-login-token expired)
        (and (null ok-p) (equal nonce "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")))))

;;; ==============================================================================
(banner "the allowlist")
;;; ==============================================================================

(ok "the owner is allowed" (glass:allowed-pubkey-p *owner*))
(ok "a guest is not" (not (glass:allowed-pubkey-p *guest*)))
(ok "case does not matter — pubkeys arrive in whatever case they were written in"
    (glass:allowed-pubkey-p (string-upcase *owner*)))
(let ((glass:*nostr-allow* '()))
  (ok "AN EMPTY ALLOWLIST DENIES EVERYONE — with nobody to authorise there is no one to say yes to"
      (and (not (glass:allowed-pubkey-p *owner*)) (not (glass:allowed-pubkey-p *guest*)))))
(ok "NIL is not a pubkey" (not (glass:allowed-pubkey-p nil)))
(ok "the allowlist can be re-read at run time, which the gateway's could not"
    (let ((glass:*nostr-allow* nil))
      (glass:refresh-nostr-allow (format nil "~a,~a" *owner* *guest*))
      (prog1 (and (glass:allowed-pubkey-p *owner*) (glass:allowed-pubkey-p *guest*))
        (glass:refresh-nostr-allow *owner*))))

;;; ==============================================================================
(banner "the enrolment store")
;;; ==============================================================================

(ok "nothing is enrolled to start with" (null (glass:list-enrolments)))
(ok "a guest is not enrolled" (not (glass:device-enrolled-p *guest*)))
(glass:enrol-device *guest*)
(ok "enrolling one makes it enrolled" (glass:device-enrolled-p *guest*))
(ok "and it is persisted — the FILE is the source of truth, not this process's memory"
    (with-open-file (s *fixture*) (search *guest* (or (read-line s nil "") ""))))
(glass:enrol-device *rando*)
(ok "two terminals, listed longest-remaining first" (= 2 (glass:enrolment-count)))

;; the mechanism the whole store was designed around: another process writes, we honour it
(let ((now (glass:unix-now)))
  (sleep 1.1)                              ; file-write-date has one-second resolution
  (with-open-file (s *fixture* :direction :output :if-exists :supersede)
    (format s "~a ~a~%" *guest* (+ now 86400)))
  (ok "a revoke performed by ANOTHER process is honoured with no restart"
      (and (glass:device-enrolled-p *guest*) (not (glass:device-enrolled-p *rando*)))))

(glass:enrol-device *rando*)
(ok "a lapsed enrolment is not an enrolment"
    (progn (glass:enrol-device *rando* -10) (not (glass:device-enrolled-p *rando*))))
(glass:enrol-device *rando*)

(ok "revoke by 8-char prefix drops exactly one"
    (and (equal (list *rando*) (glass:revoke-enrolments (subseq *rando* 0 8)))
         (not (glass:device-enrolled-p *rando*))
         (glass:device-enrolled-p *guest*)))
(glass:enrol-device *rando*)
(ok "revoke all drops everything" (and (= 2 (length (glass:revoke-enrolments "all")))
                                       (null (glass:list-enrolments))))
(ok "a prefix that matches nothing revokes nothing" (null (glass:revoke-enrolments "deadbeef")))
(ok "a prefix shorter than four characters is refused rather than matching half the fleet"
    (progn (glass:enrol-device *guest*)
           (and (null (glass:revoke-enrolments "22")) (glass:device-enrolled-p *guest*))))

;;; ==============================================================================
(banner "an enrolment is a RECORD — and `revoke' marks it rather than destroying it")
;;; ==============================================================================
;;;
;;; `<pubkey> <expiry>' could not answer any of the questions the ALREADY REDEEMED alarm makes
;;; somebody ask — how did this key get in, when, on whose authority, and was it REMOVED or did it
;;; simply LAPSE — and revoking destroyed the evidence it was performed for.  These are those
;;; questions, asked of the store after the fact.

(defun record-of (pk) (glass:device-enrolment pk))
(defun file-line-for (pk)
  "The line the FILE holds for PK, or NIL.  Asserted against the file rather than the table
wherever it matters, because the file is the half that survives a restart."
  (with-open-file (s *fixture* :if-does-not-exist nil)
    (when s (loop for l = (read-line s nil) while l
                  when (eql 0 (search pk l)) return l))))

(glass:revoke-enrolments "all")
(let ((glass:*enrolments* (make-hash-table :test 'equal)))
  (declare (ignore glass:*enrolments*)))          ; (kept explicit: nothing is cached across this)

(format t "~&   -- what a record carries --~%")
(let ((term (namedkey "4ec00001")))
  (glass:enrol-device term glass:*enrolment-ttl*
                      :via :code :nonce "cafebabecafebabecafebabecafebabe" :for *owner*)
  (let ((r (record-of term)))
    (ok "an admitted terminal has a record, not a row" (typep r 'glass:enrolment))
    (ok "  …active, with an expiry" (and (eq :active (glass:enrolment-state r))
                                         (> (glass:enrolment-expiry r) (glass:unix-now))))
    (ok "  …WHAT ADMITTED IT" (eq :code (glass:enrolment-via r)))
    (ok "  …ITS PROVENANCE: the nonce it traded, and who that code was minted for"
        (and (equal "cafebabecafebabecafebabecafebabe" (glass:enrolment-nonce r))
             (equal *owner* (glass:enrolment-issued r))))
    (ok "  …when it was created and when it was last seen"
        (and (plusp (glass:enrolment-created r)) (plusp (glass:enrolment-seen r))))
    (ok "  …and the cause of the state it is in" (equal "first-admission" (glass:enrolment-cause r)))
    (ok "and every field of it is on disk, in one greppable line"
        (let ((l (file-line-for term)))
          (and l (search "active" l) (search "code" l) (search "cafebabe" l)
               (search (subseq *owner* 0 8) l)))
        (file-line-for term)))
  ;; RENEWAL MOVES THE CLOCKS AND NOT THE PROVENANCE.  Every admission after the first is `device';
  ;; a record that reported the LAST one would answer "how did this key get in" with "it was
  ;; already in", which is no answer at all.
  (let ((created (glass:enrolment-created (record-of term))))
    (sleep 1.1)
    (glass:enrol-device term glass:*enrolment-ttl* :via :device)
    (let ((r (record-of term)))
      (ok "a renewal moves LAST SEEN" (> (glass:enrolment-seen r) created))
      (ok "  …and leaves CREATED and the provenance exactly where they were"
          (and (eql created (glass:enrolment-created r))
               (eq :code (glass:enrolment-via r))
               (equal *owner* (glass:enrolment-issued r)))))))

(format t "~&   -- revoked and expired are different ends, and both are findable --~%")
(let ((gone (namedkey "4ec10002")) (lapsed (namedkey "4ec20003")) (at (glass:unix-now)))
  (glass:enrol-device gone glass:*enrolment-ttl* :via :code)
  (glass:enrol-device lapsed -5 :via :device)          ; already past its expiry
  (glass:revoke-enrolments (subseq gone 0 8) :by *owner*)
  (let ((r (record-of gone)) (l (record-of lapsed)))
    (ok "A REVOKED ENROLMENT IS STILL THERE — the line was marked, not deleted"
        (and r (eq :revoked (glass:enrolment-state r))))
    (ok "  …with the time it happened" (>= (glass:enrolment-since r) at))
    (ok "  …and the CAUSE, naming the authority it was performed on"
        (equal (format nil "revoked-by-~a" (subseq *owner* 0 8)) (glass:enrolment-cause r))
        (glass:enrolment-cause r))
    (ok "  …and it admits nobody, which is the actual job" (not (glass:device-enrolled-p gone)))
    (ok "AN EXPIRED ONE IS DISTINGUISHABLE FROM IT — a different state and a different cause"
        (and l (eq :expired (glass:enrolment-state l)) (equal "lapsed" (glass:enrolment-cause l))))
    (ok "neither is listed as enrolled, and neither is in the live pairs LIST-ENROLMENTS returns"
        (notany (lambda (p) (member (car p) (list gone lapsed) :test #'equal))
                (glass:list-enrolments)))
    (ok "but both are in the records, asked for by state"
        (and (member gone (glass:list-enrolment-records :state :revoked)
                     :key #'glass:enrolment-pubkey :test #'equal)
             (member lapsed (glass:list-enrolment-records :state :expired)
                     :key #'glass:enrolment-pubkey :test #'equal)))
    (ok "and FIND-ENROLMENTS answers the question an alarm actually asks — by prefix, any state"
        (equal (list gone) (mapcar #'glass:enrolment-pubkey
                                   (glass:find-enrolments (subseq gone 0 8))))))
  ;; THE COMPATIBILITY PROPERTY.  A reader that knows nothing about states takes `$1 $2' — so a
  ;; revoked record has to read as one that has run out, or keeping the line would be WORSE than
  ;; deleting it: an unaware reader would report a revoked terminal as enrolled.
  (let* ((l (file-line-for gone))
         (w (and l (glass:normalize-pubkey (subseq l 0 64))))
         (exp (and l (parse-integer (subseq l 65 (position #\Space l :start 65))))))
    (ok "TO A TWO-FIELD READER a revoked record reads as one that has expired"
        (and w (equal w gone) (<= exp (glass:unix-now)))
        l))
  (ok "and a revoked key that comes back gets a new record saying so"
      (progn (glass:enrol-device gone glass:*enrolment-ttl* :via :code)
             (and (glass:device-enrolled-p gone)
                  (equal "re-admitted-after-revoke" (glass:enrolment-cause (record-of gone)))))))

(format t "~&   -- and a reader never sees the store mid-rewrite, which is how this broke before --~%")
;; THE BUG THIS IS AGAINST: %SAVE-ENROLMENTS opens the file for :SUPERSEDE, which TRUNCATES it.  A
;; reader that syncs on an mtime change between the truncation and the write reloads from an EMPTY
;; file — and if the writer's own mtime lands last, nothing ever re-reads and every terminal is
;; un-enrolled until something else touches the file.  It went unnoticed for as long as nothing
;; admitted two peers at the same instant.  The records made the write longer, so the window would
;; be wider, so it is run again rather than assumed.
(let ((floor* (glass:enrolment-count)) (dips 0) (stop nil))
  (let ((watcher (sb-thread:make-thread
                  (lambda ()
                    (loop until stop do
                      (when (< (glass:enrolment-count) floor*) (incf dips))))
                  :name "enrolment-reader")))
    (let ((writers (loop for i below 12
                         collect (let ((i i))
                                   (sb-thread:make-thread
                                    (lambda ()
                                      (dotimes (k 20)
                                        (glass:enrol-device
                                         (namedkey (format nil "c0~2,'0d~2,'0d00" i k))
                                         glass:*enrolment-ttl* :via :code)))
                                    :name "enrolment-writer")))))
      (mapc #'sb-thread:join-thread writers))
    (setf stop t)
    (sb-thread:join-thread watcher))
  (ok "240 concurrent enrolments, read continuously: THE COUNT NEVER DIPS"
      (zerop dips)
      (format nil "started at ~d, ended at ~d, dips: ~d" floor* (glass:enrolment-count) dips))
  (ok "  …and all of them are in the file, which is the half that survives a restart"
      (let ((glass:*enrolments* (make-hash-table :test 'equal))
            (glass::*enrolments-mtime* nil))
        (= (glass:enrolment-count) (+ floor* 240)))))
;; …and put the store back the way the checks below expect to find it
(dolist (e (glass:list-enrolment-records))
  (when (eql 0 (search "c0" (glass:enrolment-pubkey e)))
    (glass:revoke-enrolments (subseq (glass:enrolment-pubkey e) 0 8))))

(format t "~&   -- migration: the two-field file this box used to write --~%")
(let ((old (namedkey "01d10004")) (older (namedkey "01d20005")))
  (sleep 1.1)                                   ; file-write-date has one-second resolution
  (with-open-file (s *fixture* :direction :output :if-exists :supersede)
    (format s "~a ~a~%~a ~a~%" old (+ (glass:unix-now) 86400) older (- (glass:unix-now) 10)))
  (glass:sync-enrolments)
  (ok "A TWO-FIELD LINE LOADS AS AN ACTIVE ENROLMENT — no conversion step and no flag day"
      (and (glass:device-enrolled-p old) (eq :active (glass:enrolment-state (record-of old)))))
  (ok "  …with the history it does not have left honestly empty"
      (and (zerop (glass:enrolment-created (record-of old)))
           (null (glass:enrolment-via (record-of old)))))
  (ok "  …and a lapsed two-field line is expired, not enrolled"
      (and (not (glass:device-enrolled-p older))
           (eq :expired (glass:enrolment-state (record-of older)))))
  ;; A RESTART: the file is all there is, and it must not lose an enrolment.
  (glass:enrol-device old glass:*enrolment-ttl* :via :device)      ; rewrites in the new format
  (let ((glass:*enrolments* (make-hash-table :test 'equal))
        (glass::*enrolments-mtime* nil))
    (ok "AND A RESTART PRESERVES THE ENROLMENTS — a fresh table, read from the file alone"
        (and (glass:device-enrolled-p old) (not (glass:device-enrolled-p older))))
    (ok "  …including the settled records, which is what makes them findable tomorrow"
        (eq :expired (glass:enrolment-state (record-of older))))))

(format t "~&   -- and a HOT PATCH over a running desktop does not silently deny everybody --~%")
;; *ENROLMENTS* is a DEFVAR, so an image that loads this file while it is serving keeps the table it
;; had — and before this change that table was `pubkey -> expiry integer'.  Those read as `not
;; enrolled', and the file has not changed, so nothing would re-read.  Simulated exactly: put the old
;; shape back under a live sync.
(let ((patched (namedkey "40714001")))
  (glass:enrol-device patched)
  (sb-thread:with-mutex (glass::*enrolments-lock*)
    (clrhash glass:*enrolments*)
    (setf (gethash patched glass:*enrolments*) (+ (glass:unix-now) 86400)))   ; the OLD shape
  (ok "a table left over from the previous build is re-read from the file, not believed"
      (and (glass:device-enrolled-p patched)
           (typep (record-of patched) 'glass:enrolment)))
  (glass:revoke-enrolments (subseq patched 0 8)))

(format t "~&   -- retention: two weeks by default, and zero really means nothing is kept --~%")
(ok "the default is a fortnight" (eql 1209600 glass:*audit-retention*))
(let ((old (namedkey "0edd0006")))
  (glass:enrol-device old -100 :via :code)
  (ok "a record settled inside the window is kept" (not (null (record-of old))))
  (let ((glass:*audit-retention* 50))
    ;; the boundary: settled 100 s ago, a 50 s window.  The prune runs on the next write.
    (glass:enrol-device (namedkey "0ede0007") glass:*enrolment-ttl*)
    (ok "RETENTION PRUNES AT THE BOUNDARY — one settled longer ago than the window is gone"
        (and (null (record-of old)) (null (file-line-for old))))))
(let ((glass:*audit-retention* 0)
      (live (namedkey "0e000008")) (dead (namedkey "0e010009")))
  (glass:enrol-device live glass:*enrolment-ttl* :via :code :nonce "deadbeef" :for *owner*)
  (glass:enrol-device dead glass:*enrolment-ttl* :via :code)
  (glass:revoke-enrolments (subseq dead 0 8) :by *owner*)
  (ok "AT ZERO A REVOKED RECORD IS GONE IMMEDIATELY — the opt-out is real, not a shorter window"
      (and (null (record-of dead)) (null (file-line-for dead))))
  (ok "  …and nothing that constitutes a log is written for a LIVE one either"
      (let ((r (record-of live)))
        (and (glass:device-enrolled-p live)
             (zerop (glass:enrolment-created r)) (zerop (glass:enrolment-seen r))
             (null (glass:enrolment-via r)) (null (glass:enrolment-nonce r))
             (null (glass:enrolment-issued r)))))
  (ok "  …so the file is the two-field store this box kept before any of this"
      (let ((l (file-line-for live)))
        (and l (= 2 (length (remove "" (glass::%split-on l #\Space) :test #'string=)))))
      (file-line-for live)))
(ok "and turning it back on does not retroactively invent a history"
    (zerop (glass:enrolment-created (record-of (namedkey "0e000008")))))

;;; ==============================================================================
(banner "admission — three ways in, first match wins")
;;; ==============================================================================

(glass:revoke-enrolments "all")
(let ((code (glass:mint-login-token :ttl 900)))
  (multiple-value-bind (via token status) (glass:admit-peer *rando* code)
    (ok "a valid code admits a stranger — that is what a magic link is for" (eq :code via))
    (ok "  …and it is reported as :OK" (eq :ok status))
    (ok "  …and a renewal token rides back, so reconnecting never needs a new link"
        (and token (glass:verify-login-token token)))
    (ok "  …and the caller is now an enrolled terminal" (glass:device-enrolled-p *rando*))))

(multiple-value-bind (via token status) (glass:admit-peer *rando* nil)
  (ok "the enrolled terminal gets back in with no code at all" (eq :device via))
  (ok "  …still with a renewal" (not (null token)))
  (ok "  …and the missing code is reported as :ABSENT, not as a bad one" (eq :absent status)))

(multiple-value-bind (via token) (glass:admit-peer *owner* nil)
  (ok "the owner is admitted by the allowlist" (eq :allowlist via))
  (ok "and is handed NO bearer credential — an owner has a signer and does not need one"
      (null token)))

;;; ---- THE FACT THE CLIENT COULD NOT OTHERWISE HAVE ----------------------------
;;; A denial is answered with SILENCE by design, so a browser holding a lapsed device key had no way
;;; to learn that except by offering into the dark and concluding by timeout — half a minute of a
;;; page looking broken before it could offer the way back in.  So an admission says when the
;;; enrolment it just granted runs out, and the browser stores it against this box.

(format t "~&   -- an admission says when the enrolment it granted runs out --~%")
(let ((peer (namedkey "e5911001")))
  (multiple-value-bind (via nil* nil** expires) (glass:admit-peer peer (glass:mint-login-token :ttl 900))
    (declare (ignore nil* nil**))
    (ok "ADMIT-PEER hands back the enrolment's EXPIRY as its fourth value" (eq :code via))
    (ok "  …and it is the store's own answer, not a guess"
        (and (integerp expires)
             (eql expires (glass:enrolment-expiry (glass:device-enrolment peer)))))
    (ok "  …a whole *ENROLMENT-TTL* into the future"
        (> expires (+ (glass:unix-now) (- glass:*enrolment-ttl* 60)))))
  (multiple-value-bind (via nil* nil** expires) (glass:admit-peer peer nil)
    (declare (ignore nil* nil**))
    (ok "a reconnecting terminal is told the RENEWED expiry, which is what keeps the number true"
        (and (eq :device via) (integerp expires))))
  (ok "and a refused peer is told nothing, because nothing was enrolled"
      (null (nth-value 3 (glass:admit-peer (namedkey "e5911002") "garbage")))))

(multiple-value-bind (via nil* status) (glass:admit-peer *guest* "garbage")
  (declare (ignore nil*))
  (ok "a stranger with a bad code is refused" (null via))
  (ok "  …and the reason says WHY, so a locked-out person is diagnosable" (eq :bad status)))

(ok "a refused peer is NOT enrolled — a denial that enrolled would be the bug that matters"
    (not (glass:device-enrolled-p *guest*)))

;; The owner is by now an ENROLLED terminal too — ADMIT-PEER enrols everyone it admits — so the
;; peer used here has to be one that has never been let in, or this would be checking the device
;; path while claiming to check the allowlist one.
(let ((glass:*nostr-allow* '())
      (never "4444444444444444444444444444444444444444444444444444444444444444"))
  (ok "with no allowlist, no enrolment and no code, nobody is admitted"
      (and (null (glass:admit-peer never nil))
           (not (glass:device-enrolled-p never)))))

;;; ==============================================================================
(banner "a code is REDEEMED — once, by one key, and the honest retry still passes")
;;; ==============================================================================
;;;
;;; The property: A SUCCESSFUL REDEMPTION MEANS NOBODY ELSE USED THAT CODE.  What makes it hard is
;;; that the client legitimately re-presents one — signalling is one-shot and non-trickle over three
;;; relays with no renegotiation, so a lost answer means the phone re-offers with the same code, and
;;; fan-out delivers the same offer several times regardless.  A strict burn refuses that retry and
;;; strands the user, and the failure looks EXACTLY like the bug being fixed.  So the two cases are
;;; tested against each other here, not one at a time.

(glass:revoke-enrolments "all")
(setf glass:*login-codes* (make-instance 'glass:login-code-store))
(ignore-errors (delete-file (glass:login-code-file)))

(defparameter *alice* (hexkey #xA11CE))
(defparameter *mallory* (hexkey #x27A11))

(defun quietly (thunk)
  "Run THUNK with the leak alarm captured rather than printed.  Returns (values RESULT SAID)."
  (let* ((noise (make-string-output-stream))
         (r (let ((*error-output* noise)) (multiple-value-list (funcall thunk)))))
    (values r (get-output-stream-string noise))))

(defun holder-of (token)
  "The key the store says redeemed TOKEN's nonce, or NIL."
  (let ((c (glass:find-login-code (nth-value 1 (glass:verify-login-token token)))))
    (and c (glass:code-redeemer c))))

(defun state-of (token)
  (let ((c (glass:find-login-code (nth-value 1 (glass:verify-login-token token)))))
    (and c (glass:code-state c))))

(format t "~&   -- two different keys, one code: first wins --~%")
(let ((code (glass:mint-login-token :ttl 900)))
  (multiple-value-bind (via token status) (glass:admit-peer *alice* code)
    (ok "the first key to present a code is admitted :code" (eq :code via))
    (ok "  …with status :ok" (eq :ok status))
    (ok "  …and is enrolled — the code was TRADED for the enrolment"
        (and token (glass:device-enrolled-p *alice*)))
    (ok "  …and the store says :redeemed, by that key, and not merely `spent'"
        (and (eq :redeemed (state-of code)) (equal *alice* (holder-of code)))))
  ;; the interceptor.  Loud on *error-output* by design, so it is captured rather than muted:
  ;; a refusal nobody can see is not the feature.
  (multiple-value-bind (r said) (quietly (lambda () (glass:admit-peer *mallory* code)))
    (ok "a DIFFERENT key presenting the same code is REFUSED" (null (first r)))
    (ok "  …with :spent, which is a different denial from :bad, :expired and :superseded"
        (eq :spent (third r)))
    (ok "  …and it is not enrolled by the attempt" (not (glass:device-enrolled-p *mallory*)))
    (ok "  …and it is LOGGED LOUDLY — the only signal this system has that a link leaked"
        (and (search "ALREADY REDEEMED" said) (search (subseq *alice* 0 8) said)
             (search (subseq *mallory* 0 8) said))
        (string-trim '(#\Newline #\Space) (subseq said 0 (min 96 (length said))))))
  (ok "the first key still holds it after the attempt" (equal *alice* (holder-of code))))

(format t "~&   -- the SAME key, twice: the retry case, which is the one that breaks users --~%")
(let ((code (glass:mint-login-token :ttl 900))
      (bob (hexkey #xB0B)))
  (ok "first presentation admits" (eq :code (glass:admit-peer bob code)))
  (ok "second presentation of the same code ALSO admits, via :code and not merely as a device"
      (eq :code (glass:admit-peer bob code)))
  (multiple-value-bind (via nil* status) (glass:admit-peer bob code)
    (declare (ignore nil*))
    (ok "  …a third time too, still :ok — relay fan-out delivers one offer several times"
        (and (eq :code via) (eq :ok status))))
  (ok "and the store holds ONE row for it, still naming that key"
      (equal bob (holder-of code))))

(format t "~&   -- and a probe does not spend: :ENROL NIL asks, it does not trade --~%")
(let ((code (glass:mint-login-token :ttl 900))
      (p (hexkey #x9805E)) (q (hexkey #x9805F)))
  (ok "a non-enrolling call says the code would be accepted"
      (eq :code (glass:admit-peer p code :enrol nil)))
  (ok "  …and did NOT bind it — somebody else can still be the first to redeem"
      (eq :code (glass:admit-peer q code)))
  (ok "  …after which the prober is the one who is too late"
      (null (first (quietly (lambda () (glass:admit-peer p code)))))))

;;; ---- REDEMPTION IS NOT CONTINGENT ON NEED ------------------------------------
;;; This is the case that works TODAY BY ACCIDENT: the client sends a code whenever it has one, and
;;; the box's first-match COND puts `code' ahead of `device', so an already-enrolled terminal
;;; redeems anyway.  Nothing stated it, and the obvious optimisation — "we have an enrolment, skip
;;; the code" — would silently stop burning anything and leave live codes in DMs with no test
;;; failing.  So it is stated in ADMIT-PEER and asserted here.

(format t "~&   -- a tapped link burns its code even when the terminal did not need it --~%")
(let ((already (hexkey #xE47011)))
  (glass:enrol-device already)
  (ok "the terminal is already enrolled and would be admitted with no code at all"
      (and (glass:device-enrolled-p already) (eq :device (glass:admit-peer already nil))))
  (let ((code (glass:mint-login-token :ttl 900)))
    (multiple-value-bind (via nil* status) (glass:admit-peer already code)
      (declare (ignore nil*))
      (ok "presenting a code anyway is reported via=:code, ahead of the enrolment it did not need"
          (eq :code via))
      (ok "  …status :ok" (eq :ok status)))
    (ok "  …and THE CODE IS SPENT: redemption is not contingent on need"
        (and (eq :redeemed (state-of code)) (equal already (holder-of code))))
    (ok "  …so nobody else can use the link that terminal already tapped"
        (eq :spent (third (quietly (lambda () (glass:admit-peer (hexkey #xF00F) code))))))))
;; the same, for an ALLOWLISTED caller — whose standing is permanent and who needs a code least
(let ((code (glass:mint-login-token :ttl 900)))
  (ok "an allowlisted owner presenting a code is via=:code, not via=:allowlist"
      (eq :code (glass:admit-peer *owner* code)))
  (ok "  …and burns it too — a link the owner tapped must not stay live in their DMs"
      (and (eq :redeemed (state-of code)) (equal *owner* (holder-of code)))))

;;; ---- ATOMICITY.  Not by inspection: by running the race. ---------------------
;;; Two racing redemptions that both see the nonce unspent is the whole property lost to a missing
;;; lock, and it is the failure that inspection is worst at catching — the window is a few
;;; instructions wide and a single-threaded suite never opens it.

(format t "~&   -- N threads, one code, many rounds --~%")
(defparameter *race-threads* 32)
(defparameter *race-rounds* 150)

(let ((two-winners 0) (no-winner 0) (wrong-holder 0) (total 0) (t0 (get-internal-real-time)))
  (dotimes (round *race-rounds*)
    (let* ((code (glass:mint-login-token :ttl 900))
           (nonce (nth-value 1 (glass:verify-login-token code)))
           (exp (nth-value 2 (glass:verify-login-token code)))
           (start (sb-thread:make-semaphore))
           (results (make-array *race-threads* :initial-element nil))
           (threads
             (loop for i below *race-threads*
                   collect (let ((i i))
                             (sb-thread:make-thread
                              (lambda ()
                                ;; every thread parks on the semaphore and is released together, so
                                ;; they arrive at the critical section at once rather than in the
                                ;; order they were spawned
                                (sb-thread:wait-on-semaphore start)
                                (setf (aref results i)
                                      (multiple-value-list
                                       (glass:redeem-nonce nonce (hexkey (+ #x100000 i)) exp))))
                              :name "race")))))
      (sb-thread:signal-semaphore start *race-threads*)
      (mapc #'sb-thread:join-thread threads)
      (incf total *race-threads*)
      (let* ((winners (loop for r across results when (eq :bound (second r)) collect (third r)))
             (held (holder-of code)))
        (cond ((> (length winners) 1) (incf two-winners))
              ((null winners) (incf no-winner)))
        ;; and the winner has to be the key the STORE says holds it — one thread returning :BOUND
        ;; while a later one overwrote the binding would be the same bug wearing a disguise
        (unless (and (= 1 (length winners)) (equal held (first winners)))
          (incf wrong-holder)))))
  (let ((ms (round (* 1000 (- (get-internal-real-time) t0)) internal-time-units-per-second)))
    (ok "exactly ONE binding per code, every round — no round produced two winners"
        (zerop two-winners)
        (format nil "~d rounds x ~d threads = ~d concurrent redemptions in ~dms; ~
                     rounds with two winners: ~d"
                *race-rounds* *race-threads* total ms two-winners))
    (ok "  …and never zero winners either — a lock that refused everybody would also `pass'"
        (zerop no-winner))
    (ok "  …and the winner is the key the store says holds the code" (zerop wrong-holder))))

(format t "~&   -- and the same race through the whole of ADMIT-PEER, enrolment and all --~%")
(let ((bad 0) (rounds 30) (n 12))
  (dotimes (round rounds)
    (let* ((code (glass:mint-login-token :ttl 900))
           (start (sb-thread:make-semaphore))
           (out (make-array n :initial-element nil))
           (keys (loop for i below n collect (hexkey (+ #x200000 (* round 100) i))))
           (threads (loop for i below n
                          for k in keys
                          collect (let ((i i) (k k))
                                    (sb-thread:make-thread
                                     (lambda ()
                                       ;; BOUND INSIDE THE THREAD.  A new SBCL thread starts from
                                       ;; the GLOBAL value of a special, not from the binding in
                                       ;; force where MAKE-THREAD was called — so a LET around the
                                       ;; spawn loop silences nothing, and the n-1 leak alarms come
                                       ;; out interleaved across the suite's own output.
                                       (let ((*error-output* (make-broadcast-stream)))
                                         (sb-thread:wait-on-semaphore start)
                                         (setf (aref out i)
                                               (multiple-value-list (glass:admit-peer k code)))))
                                     :name "admit-race")))))
      (sb-thread:signal-semaphore start n)
      (mapc #'sb-thread:join-thread threads)
      (let ((admitted (loop for r across out count (eq :code (first r))))
            (enrolled (count-if #'glass:device-enrolled-p keys)))
        ;; exactly one admitted on the code, and exactly one enrolment bought with it
        (unless (and (= 1 admitted) (= 1 enrolled)) (incf bad)))))
  (ok "one admission and one enrolment per code, under concurrency, through the real entry point"
      (zerop bad)
      (format nil "~d rounds x ~d threads through ADMIT-PEER; bad rounds: ~d" rounds n bad)))

;;; ==============================================================================
(banner "a code nobody tapped: MINTING SUPERSEDES, so at most one link per person is live")
;;; ==============================================================================
;;;
;;; Single use closes "somebody else redeemed it".  It does nothing about the commonest shape there
;;; is — ask for a link, tap nothing, ask again — where the first link stays armed in a DM for the
;;; rest of its TTL.  A LINK MINTED FOR A RECIPIENT CANCELS THAT RECIPIENT'S EARLIER OUTSTANDING
;;; CODES, in the same critical section that mints it.

(format t "~&   -- ask twice, tap the first: refused, and told why --~%")
(let* ((rcpt (hexkey #x5EC0))
       (first-link (glass:mint-login-token :ttl 900 :for rcpt)))
  (ok "a link minted :FOR somebody is recorded as :outstanding" (eq :outstanding (state-of first-link)))
  (ok "  …with that recipient on it, which is what forms a supersede group"
      (equal rcpt (glass:code-recipient (glass:find-login-code
                                         (nth-value 1 (glass:verify-login-token first-link))))))
  (multiple-value-bind (second-link killed) (glass:mint-login-token :ttl 900 :for rcpt)
    (ok "asking again supersedes the first, and says how many it cancelled" (eql 1 killed))
    (ok "  …the older link is now :superseded in the store" (eq :superseded (state-of first-link)))
    (ok "  …and the newer one is the live one" (eq :outstanding (state-of second-link)))
    (ok "TAPPING THE OLDER LINK IS REFUSED" (null (glass:admit-peer (hexkey #x5EC1) first-link)))
    (ok "  …with :superseded — `ask for a fresh one', which is NOT the leak alarm"
        (eq :superseded (nth-value 2 (glass:admit-peer (hexkey #x5EC1) first-link))))
    (ok "  …and the newer link still works" (eq :code (glass:admit-peer (hexkey #x5EC2) second-link)))))

(format t "~&   -- but only the recipient's OWN outstanding codes, and only outstanding ones --~%")
(let* ((mine (hexkey #x11AA)) (theirs (hexkey #x22BB))
       (my-link (glass:mint-login-token :ttl 900 :for mine))
       (their-link (glass:mint-login-token :ttl 900 :for theirs)))
  (glass:mint-login-token :ttl 900 :for mine)
  (ok "a mint for ME does not touch a link minted for SOMEBODY ELSE"
      (eq :outstanding (state-of their-link)))
  (ok "  …while mine is superseded" (eq :superseded (state-of my-link)))
  (ok "  …and theirs still admits" (eq :code (glass:admit-peer (hexkey #x22BC) their-link))))

(let* ((sitting (hexkey #x51771))
       (link (glass:mint-login-token :ttl 900 :for sitting)))
  (ok "a link that has ALREADY BEEN REDEEMED is not superseded by a later mint"
      (and (eq :code (glass:admit-peer sitting link))
           (progn (glass:mint-login-token :ttl 900 :for sitting)
                  (eq :redeemed (state-of link)))))
  (ok "  …so the terminal sitting on it keeps reconnecting — a new link must not log anybody out"
      (eq :code (glass:admit-peer sitting link))))

(format t "~&   -- superseding is atomic with minting: N mints for one recipient, one survivor --~%")
(let ((bad 0) (rounds 60) (n 16))
  (dotimes (round rounds)
    (let* ((rcpt (hexkey (+ #x300000 round)))
           (start (sb-thread:make-semaphore))
           (out (make-array n :initial-element nil))
           (threads (loop for i below n
                          collect (let ((i i))
                                    (sb-thread:make-thread
                                     (lambda ()
                                       (sb-thread:wait-on-semaphore start)
                                       (setf (aref out i)
                                             (glass:mint-login-token :ttl 900 :for rcpt)))
                                     :name "mint-race")))))
      (sb-thread:signal-semaphore start n)
      (mapc #'sb-thread:join-thread threads)
      ;; whichever mint landed last, EXACTLY ONE of the N codes may still be outstanding
      (let ((live (count :outstanding (coerce out 'list) :key #'state-of)))
        (unless (= 1 live) (incf bad)))))
  (ok "exactly one outstanding code survives each concurrent burst of mints"
      (zerop bad)
      (format nil "~d rounds x ~d concurrent mints for one recipient; rounds with != 1 live: ~d"
              rounds n bad)))

;;; ---- WHAT MUST NOT SUPERSEDE -------------------------------------------------
;;; The trap the user named: "they are already logged in, burn their outstanding codes".  A phone on
;;; its enrolment and a laptop that was just sent a link are the same person, and burning on the
;;; phone's reconnect kills the laptop's link before anybody taps it — failing exactly the way an
;;; intercepted code fails, which is the one distinction this store exists to make legible.

(format t "~&   -- an admission burns nothing but the code it was handed --~%")
(let* ((person (hexkey #x1AB70))
       (laptop-link (glass:mint-login-token :ttl 900 :for person)))
  ;; the phone reconnects, repeatedly, on its enrolment and on renewals
  (glass:enrol-device person)
  (dotimes (i 5) (glass:admit-peer person nil))
  (ok "A LINK MINTED FOR A PERSON SURVIVES THAT PERSON RECONNECTING ON THEIR ENROLMENT"
      (eq :outstanding (state-of laptop-link)))
  (ok "  …and is still tappable afterwards, by the browser it was sent to"
      (eq :code (glass:admit-peer (hexkey #x1AB71) laptop-link))))

(format t "~&   -- and a RENEWAL supersedes nothing, because it has no recipient --~%")
(let* ((person (hexkey #x8E11))
       (pending (glass:mint-login-token :ttl 900 :for person))
       (code (glass:mint-login-token :ttl 900))
       (issued (list code))
       (all-code t))
  (dotimes (i 20)
    (multiple-value-bind (via token) (glass:admit-peer person code)
      (unless (eq :code via) (setf all-code nil))
      (push token issued)
      (setf code token)))
  (ok "twenty reconnects in a row, each on the renewal the last one handed back, all via :code"
      all-code)
  (ok "  …and the link that was outstanding for that same person is UNTOUCHED by all of it"
      (eq :outstanding (state-of pending)))
  (let ((nonces (mapcar (lambda (tk) (nth-value 1 (glass:verify-login-token tk))) issued)))
    (ok "  …every renewal nonce is DISTINCT — no renewal ever arrives already spent"
        (and (notany #'null nonces)
             (= (length nonces) (length (remove-duplicates nonces :test #'equal))))
        (format nil "~d issued, ~d distinct" (length nonces)
                (length (remove-duplicates nonces :test #'equal))))
    (ok "  …no renewal is ever recorded with a recipient, so none can join a supersede group"
        (every (lambda (n) (let ((c (glass:find-login-code n)))
                             (or (null c) (null (glass:code-recipient c)))))
               nonces))
    (ok "  …and each was redeemable exactly ONCE: a thief holding a used renewal is refused"
        (eq :spent (third (quietly (lambda ()
                                     (glass:admit-peer (hexkey #x7417F) (second issued)))))))
    (ok "  …while the renewal that was never presented is still redeemable"
        (eq :code (glass:admit-peer (hexkey #xFEED11) (first issued)))))
  (ok "the mint is distinct per call at volume too — 200 mints, 200 nonces"
      (= 200 (length (remove-duplicates
                      (loop repeat 200
                            collect (nth-value 1 (glass:verify-login-token
                                                  (glass:mint-login-token :ttl 900))))
                      :test #'equal)))))

;;; ==============================================================================
(banner "expiry, pruning, and a restart that does not resurrect anything")
;;; ==============================================================================

(format t "~&   -- expiry still refuses on its own, and rows are pruned at it --~%")
(let* ((short (glass:mint-login-token :ttl 1))
       (owner-of-it (hexkey #x5405)))
  (ok "a one-second code admits while it is alive" (eq :code (glass:admit-peer owner-of-it short)))
  (sleep 2)
  (multiple-value-bind (via nil* status) (glass:admit-peer owner-of-it short :enrol nil)
    (declare (ignore nil*))
    (ok "once expired it is :EXPIRED even for the key that redeemed it — a binding is not a bypass"
        (eq :expired status))
    (ok "  …and that key is still admitted, as the enrolled DEVICE it became" (eq :device via)))
  (ok "  …and a stranger gets :expired rather than :spent — expiry is checked first, and is the
       unremarkable one a failure screen must be able to tell apart from the rest"
      (eq :expired (third (quietly (lambda () (glass:admit-peer (hexkey #x5406) short))))))
  ;; ---- THE TWO LIFETIMES, PROVED APART ---------------------------------------------------
  ;; A spent code has two clocks and they are not the same clock.  For CORRECTNESS the nonce need
  ;; only be remembered until it expires — minutes — because the MAC refuses it from that instant
  ;; with no help from any store.  For FORENSICS the redemption is worth keeping for the whole
  ;; retention window: `who traded that link' is the question the leak alarm makes somebody ask,
  ;; and it is asked hours later.  One number for both gives an unbounded store or an empty audit
  ;; trail exactly for the codes that mattered.  This is where they are shown to be separate.
  (let ((nonce (nth-value 1 (glass:verify-login-token short))))
    (ok "the row was written while the code was live" (search nonce (slurp (glass:login-code-file))))
    ;; the prune runs inside the next transition's critical section
    (glass:redeem-nonce (hexkey #xF00D) (hexkey #xBEEF) (+ (glass:unix-now) 900))
    (let ((row (glass:find-login-code nonce)))
      (ok "THE REDEMPTION RECORD SURVIVES THE CODE — the row is still there after its expiry"
          (and row (eq :redeemed (glass:code-state row))))
      (ok "  …still naming the key that traded it, which is the whole forensic point"
          (and row (equal owner-of-it (glass:code-redeemer row))))
      (ok "  …and it is on disk, not merely in this process"
          (search nonce (slurp (glass:login-code-file))))
      (ok "  …but it is NOT redeemable: the short lifetime is the code's own expiry"
          (and row (not (glass:code-live-p row))))
      (ok "  …so REDEEM-NONCE answers :EXPIRED even to the key that holds it, record or no record"
          (multiple-value-bind (ok* state) (glass:redeem-nonce owner-of-it nonce
                                                              (glass:code-expiry row))
            (and (null ok*) (eq :expired state))))
      (ok "  …and a stranger cannot take it either, which a surviving row must never enable"
          (null (nth-value 0 (glass:redeem-nonce (hexkey #x5407) nonce
                                                 (glass:code-expiry row)))))
      (ok "  …and it is not counted among the live codes, so `how many are outstanding' still means it"
          (notany (lambda (c) (equal (glass:code-nonce c) nonce))
                  (remove-if-not #'glass:code-live-p (glass:list-login-codes)))))
    ;; and the LONG lifetime ends too.  With retention off, the record is dropped at the same
    ;; instant it always was — which is what makes this a dial and not a leak.
    (let ((glass:*audit-retention* 0))
      (glass:redeem-nonce (hexkey #xF00C) (hexkey #xBEEC) (+ (glass:unix-now) 900))
      (ok "WITH RETENTION AT ZERO the spent row is dropped at the code's expiry, as it always was"
          (null (glass:find-login-code nonce)))
      (ok "  …and it is gone from the file too" (not (search nonce (slurp (glass:login-code-file))))))))

(format t "~&   -- an outstanding code that nobody ever taps is pruned too --~%")
(let ((stale (glass:mint-login-token :ttl 1 :for (hexkey #x57A1E))))
  (ok "it starts outstanding" (eq :outstanding (state-of stale)))
  (sleep 2)
  (glass:redeem-nonce (hexkey #xF00E) (hexkey #xBEEE) (+ (glass:unix-now) 900))
  (ok "and after expiry it is gone from the store entirely — no state, nothing to keep"
      (and (null (state-of stale))
           (not (search (nth-value 1 (glass:verify-login-token stale))
                        (slurp (glass:login-code-file)))))))

(format t "~&   -- a restart does not resurrect a spent code --~%")
(let* ((code (glass:mint-login-token :ttl 900))
       (first-key (hexkey #x1111AA))
       (second-key (hexkey #x2222BB))
       (superseded (glass:mint-login-token :ttl 900 :for (hexkey #x3333CC))))
  (glass:mint-login-token :ttl 900 :for (hexkey #x3333CC))     ; …which supersedes it
  (ok "a code is redeemed by one key" (eq :code (glass:admit-peer first-key code)))
  (ok "  …and it is on disk, in the store beside the enrolments"
      (search (nth-value 1 (glass:verify-login-token code)) (slurp (glass:login-code-file))))
  ;; A RESTART, exactly: a brand-new store object whose only knowledge is the file.  Nothing is
  ;; carried over in memory — which is the whole thing being checked.
  (let ((glass:*login-codes* (make-instance 'glass:login-code-store)))
    (ok "a fresh store starts empty in memory and reads the file on first use"
        (plusp (glass:login-code-count)))
    (ok "AFTER THE RESTART the code is still spent — a stranger is refused"
        (null (first (quietly (lambda () (glass:admit-peer second-key code))))))
    (ok "  …and the key that traded it is still admitted on it, idempotently"
        (eq :code (glass:admit-peer first-key code)))
    (ok "  …and the store names the same holder it named before the restart"
        (equal first-key (holder-of code)))
    (ok "  …and a SUPERSEDED code is still superseded, with its reason intact and not collapsed"
        (and (eq :superseded (state-of superseded))
             (eq :superseded (nth-value 2 (glass:admit-peer (hexkey #x3333CD) superseded)))))))

;;; ==============================================================================
(banner "two TTLs, because a link and a renewal have opposite jobs")
;;; ==============================================================================
;;;
;;; These were one parameter doing both, which is why neither could be tuned.  A LINK is a
;;; credential in transit through a DM and its TTL is the only bound on a leaked one; a RENEWAL is a
;;; credential at rest in localStorage that has to survive until the browser's next load.

(ok "a LINK is minutes, not half an hour — the window a leaked link is usable for"
    (and (integerp glass:*login-ttl*) (<= glass:*login-ttl* 900))
    (format nil "*LOGIN-TTL* = ~ds" glass:*login-ttl*))
(ok "a RENEWAL is unchanged at half an hour — shortening it silently demotes code to device"
    (eql 1800 glass:*renewal-ttl*))
(ok "they are DIFFERENT parameters now, which is the whole point"
    (not (eql glass:*login-ttl* glass:*renewal-ttl*)))
(ok "the `link' DM mints at the LINK ttl"
    (let* ((r (glass:nostr-command-reply *owner* "link"))
           (at (search "&code=" r))
           (exp (nth-value 2 (glass:verify-login-token (subseq r (+ at 6))))))
      (<= (- exp (glass:unix-now)) glass:*login-ttl*)))
(ok "  …and the renewal that rides back with an admission mints at the RENEWAL ttl"
    (let* ((peer (hexkey #x77111))
           (token (nth-value 1 (glass:admit-peer peer (glass:mint-login-token :ttl 900))))
           (exp (nth-value 2 (glass:verify-login-token token))))
      (> (- exp (glass:unix-now)) glass:*login-ttl*)))
(ok "the `link' DM says its replacement replaces the earlier ones"
    (progn (glass:nostr-command-reply *owner* "link")
           (search "no longer work" (glass:nostr-command-reply *owner* "link"))))
(ok "  …and the first `link' to a person says nothing of the kind — there was nothing to replace"
    (not (search "no longer work"
                 (glass:nostr-command-reply
                  (let ((k (hexkey #x9E4)))
                    (glass:refresh-nostr-allow (format nil "~a,~a" *owner* k))
                    k)
                  "link"))))
(glass:refresh-nostr-allow *owner*)

;;; ==============================================================================
(banner "the command surface — and who may run each command")
;;; ==============================================================================

(glass:revoke-enrolments "all")
(glass:enrol-device *guest*)                       ; a device key, the bearer credential
;; *rando* is neither on the allowlist nor enrolled

(flet ((verb (s) (nth-value 0 (glass:parse-nostr-command s)))
       (arg (s) (nth-value 1 (glass:parse-nostr-command s))))
  (ok "link / devices / revoke / help are the four verbs"
      (equal '(:link :devices :revoke :help)
             (list (verb "link") (verb "devices") (verb "revoke abc12345") (verb "help"))))
  (ok "? is help" (eq :help (verb "?")))
  (ok "revoke carries its argument" (equal "abc12345" (arg "revoke abc12345")))
  (ok "case and surrounding space do not matter" (eq :link (verb "  LINK  ")))
  (ok "an SDP offer is not a command — which is what keeps this bot off the gateway's traffic"
      (null (verb (format nil "v=0~%o=- 1 1 IN IP4 0.0.0.0~%m=application 9 UDP/DTLS/SCTP webrtc-datachannel~a"
                          (make-string 200 :initial-element #\x)))))
  (ok "and neither is chatter" (null (verb "how are you")))
  (ok "`link' is matched as a substring, so `blink' mints one too — kept, and documented"
      (eq :link (verb "blink"))))

(flet ((reply (pub text) (nth-value 0 (glass:nostr-command-reply pub text)))
       (role (pub text) (nth-value 2 (glass:nostr-command-reply pub text))))
  (format t "~&   -- the owner (allowlisted) --~%")
  (ok "owner: link -> a magic link with the box npub and a live code in the fragment"
      (let ((r (reply *owner* "link")))
        (and (stringp r) (search "#box=npub1" r) (search "&code=" r))))
  ;; the reply may carry a second paragraph now ("this replaces any earlier link"), so the code is
  ;; taken up to whitespace rather than to end of string — which is what the browser does with the
  ;; fragment too
  (ok "  …and the code in it verifies"
      (let* ((r (reply *owner* "link")) (at (search "&code=" r))
             (end (or (position-if (lambda (c) (member c '(#\Space #\Newline #\Return #\Tab))) r
                                   :start (+ at 6))
                      (length r))))
        (glass:verify-login-token (subseq r (+ at 6) end))))
  (ok "owner: devices -> the list" (search "enrolled terminal" (reply *owner* "devices")))
  (ok "owner: devices all -> the record too, with what happened to the ones that are gone"
      (let ((r (progn (glass:enrol-device (namedkey "d0c00001"))
                      (glass:revoke-enrolments "d0c00001" :by *owner*)
                      (reply *owner* "devices all"))))
        (and (search "d0c00001" r) (search "REVOKED" r) (search "revoked-by-11111111" r)))
      (reply *owner* "devices all"))
  (ok "  …and a bare `devices' still shows only the live ones, which is what it always meant"
      (not (search "d0c00001" (reply *owner* "devices"))))
  (ok "owner: help -> mentions the management commands it may use"
      (let ((r (reply *owner* "help"))) (and (search "devices" r) (search "revoke" r))))
  (ok "owner is classified :allowlist" (eq :allowlist (role *owner* "help")))

  (format t "~&   -- an enrolled DEVICE: a bearer credential, and bounded like one --~%")
  (ok "device: link -> allowed.  A terminal whose code lapses can refresh itself"
      (stringp (reply *guest* "link")))
  (ok "device: devices -> DENIED.  A stolen browser key must not enumerate the fleet"
      (eq :denied (reply *guest* "devices")))
  (ok "device: revoke -> DENIED.  It must not revoke the others, or itself into permanence"
      (eq :denied (reply *guest* "revoke all")))
  (ok "  …and the enrolments it tried to revoke are all still there"
      (glass:device-enrolled-p *guest*))
  (ok "device: help -> allowed, and does NOT advertise commands it may not run"
      (let ((r (reply *guest* "help")))
        (and (stringp r) (search "link" r) (not (search "revoke" r)))))
  (ok "device is classified :device" (eq :device (role *guest* "help")))

  (format t "~&   -- a stranger: no reply at all, which is the denial --~%")
  (ok "stranger: link -> denied" (eq :denied (reply *rando* "link")))
  (ok "stranger: devices -> denied" (eq :denied (reply *rando* "devices")))
  (ok "stranger: revoke -> denied" (eq :denied (reply *rando* "revoke all")))
  (ok "stranger: help -> denied.  Even the usage is an oracle that the box is listening"
      (eq :denied (reply *rando* "help")))
  (ok "a stranger has no role" (null (role *rando* "help")))
  (ok "and a non-command is NIL rather than :denied — there is nothing to deny"
      (null (reply *rando* "hello there"))))

(ok "the owner's revoke actually revokes"
    (progn (glass:nostr-command-reply *owner* (format nil "revoke ~a" (subseq *guest* 0 8)))
           (not (glass:device-enrolled-p *guest*))))

;;; ==============================================================================
(banner "the service, over a real loopback socket")
;;; ==============================================================================

(defparameter *port* 15915)     ; not 5915: a gate must never race the desktop's own service

;; the raw wire, spoken by hand: `nc localhost 5915' has to be a diagnostic, so the bytes are
;; asserted rather than only the client library that writes them
(defun raw (line &key (expect-rows 0))
  (let ((sock (make-instance 'sb-bsd-sockets:inet-socket :type :stream :protocol :tcp)))
    (unwind-protect
         (progn
           (sb-bsd-sockets:socket-connect
            sock (sb-bsd-sockets:make-inet-address "127.0.0.1") *port*)
           (let ((s (sb-bsd-sockets:socket-make-stream sock :input t :output t
                                                            :element-type 'character
                                                            :buffering :full :timeout 5)))
             (write-string line s) (write-char #\Newline s) (force-output s)
             (let ((head (read-line s nil "")))
               (values head (loop repeat expect-rows collect (read-line s nil ""))))))
      (ignore-errors (sb-bsd-sockets:socket-close sock)))))

(glass:revoke-enrolments "all")
(defparameter *srv* (glass:start-admission-service :port *port* :install nil))
(ok "the service is listening" (not (null *srv*)))
(sleep 0.2)

(ok "ping answers with the box's posture, in one readable line"
    (let ((r (raw "glass-admit/1 ping")))
      (format t "     ~a~%" r)
      (and (eql 0 (search "glass-admit/1 ok " r))
           (search (format nil "box=~a" (glass:box-pubkey)) r)
           (search "allow=1" r))))
(ok "an unknown verb is an error and not a crash"
    (search "err reason=unknown-op" (raw "glass-admit/1 fly-me-to-the-moon")))
(ok "and so is junk on the wire" (search "err" (raw "hello")))

(let ((code (glass:mint-login-token :ttl 900)))
  (ok "admit with a good code says ok, names the way in, and hands back a renewal"
      (let ((r (raw (format nil "glass-admit/1 admit pub=~a code=~a" *rando* code))))
        (format t "     ~a~%" r)
        (and (search " ok " r) (search "via=code" r) (search "token=" r))))
  (ok "  …and the peer is now enrolled, on this desktop's side of the wire"
      (glass:device-enrolled-p *rando*)))
(ok "admit with no code and no standing is DENIED, with the reason"
    (let ((r (raw (format nil "glass-admit/1 admit pub=~a" *guest*))))
      (and (search " deny " r) (search "reason=absent" r))))
(ok "admit with a rotten code says so specifically"
    (search "reason=bad" (raw (format nil "glass-admit/1 admit pub=~a code=zzz" *guest*))))
;; the leak, over the wire.  A gateway logs whatever REASON it is handed, so `spent' has to reach it
;; as its own word — a leaked link that arrived at the far end as `bad' would be diagnosed as a typo.
(let ((code (glass:mint-login-token :ttl 900))
      (first-key (hexkey #xC0FFEE))
      (second-key (hexkey #xDECAF)))
  (ok "over the socket: the first key to present a code is admitted via=code"
      (search "via=code" (raw (format nil "glass-admit/1 admit pub=~a code=~a" first-key code))))
  (ok "  …and a second key presenting it is DENIED with reason=spent, its own word on the wire"
      (let ((r (raw (format nil "glass-admit/1 admit pub=~a code=~a" second-key code))))
        (format t "     ~a~%" r)
        (and (search " deny " r) (search "reason=spent" r))))
  (ok "  …while the first key re-presenting it is admitted again — the retry, over the protocol"
      (search "via=code" (raw (format nil "glass-admit/1 admit pub=~a code=~a" first-key code))))
  ;; and put the store back the way the checks below it expect to find it
  (glass:revoke-enrolments first-key))
(ok "allowed is the allowlist and nothing else"
    (and (search "allowed=1" (raw (format nil "glass-admit/1 allowed pub=~a" *owner*)))
         (search "allowed=0" (raw (format nil "glass-admit/1 allowed pub=~a" *rando*)))))
(ok "  …and an enrolled DEVICE is still not allowlisted, which is the whole distinction"
    (and (glass:device-enrolled-p *rando*)
         (search "allowed=0" (raw (format nil "glass-admit/1 allowed pub=~a" *rando*)))))

(multiple-value-bind (head rows) (raw "glass-admit/1 devices" :expect-rows 1)
  (ok "devices answers rows=N then N lines of `<pubkey> <expiry>'"
      (and (search "rows=1" head)
           (eql 0 (search *rando* (first rows)))
           (parse-integer (subseq (first rows) 65) :junk-allowed t))))

;;; ---- the expiry, and the record, over the wire -------------------------------
;;; The chain the client's half of this rests on: the desktop decides and knows the expiry, the
;;; reply carries it, and a transport copies it into the answer envelope.  This is the middle link.

(let ((peer (namedkey "e5911003")))
  (let ((r (raw (format nil "glass-admit/1 admit pub=~a code=~a"
                        peer (glass:mint-login-token :ttl 900)))))
    (format t "     ~a~%" r)
    (ok "ADMIT CARRIES expires= — the enrolment's own expiry, on the wire"
        (let ((at (search "expires=" r)))
          (and at (let ((v (parse-integer (subseq r (+ at 8)) :junk-allowed t)))
                    (and v (eql v (glass:enrolment-expiry (glass:device-enrolment peer))))))))
    (ok "  …and a denial carries none, because nothing was enrolled to have one"
        (let ((d (raw (format nil "glass-admit/1 admit pub=~a" (namedkey "e5911004")))))
          (and (search " deny " d) (not (search "expires=" d))))))
  ;; the record, as the panel and a shell one-liner see it
  (multiple-value-bind (head rows) (raw "glass-admit/1 devices"
                                        :expect-rows (glass:enrolment-count))
    (declare (ignore head))
    (let ((line (find peer rows :test (lambda (p l) (eql 0 (search p l))))))
      (format t "     ~a~%" line)
      (ok "THE DEVICES ROW IS THE FILE LINE — the record travels, and the first two fields are
       still `<pubkey> <expiry>' so a reader that wants only those never notices the rest"
          (let ((w (remove "" (glass::%split-on (or line "") #\Space) :test #'string=)))
            (and (= 10 (length w)) (equal peer (first w)) (equal "active" (third w))
                 (equal "code" (sixth w)))))))
  (ok "and ADMISSION-RECORDS parses it back into a plist a projection can map over"
      (let ((r (find peer (glass:admission-records :host "127.0.0.1" :port *port*)
                     :key (lambda (p) (getf p :pubkey)) :test #'equal)))
        (and r (eq :active (getf r :state)) (eq :code (getf r :via))
             (integerp (getf r :expiry)) (plusp (getf r :created)))))
  (glass:revoke-enrolments peer :by *owner*)
  (ok "  …and `state=all' is how the settled ones are asked for, which the default never returns"
      (let ((live (glass:admission-records :host "127.0.0.1" :port *port*))
            (all (glass:admission-records :state :all :host "127.0.0.1" :port *port*)))
        (and (not (find peer live :key (lambda (p) (getf p :pubkey)) :test #'equal))
             (let ((r (find peer all :key (lambda (p) (getf p :pubkey)) :test #'equal)))
               (and r (eq :revoked (getf r :state))
                    (equal (format nil "revoked-by-~a" (subseq *owner* 0 8)) (getf r :cause))))))))

(ok "revoke on a stranger's authority is DENIED — the rule is enforced here, not at the surface"
    (search "deny reason=not-allowed"
            (raw (format nil "glass-admit/1 revoke pub=~a arg=all" *guest*))))
(ok "  …and nothing was revoked" (glass:device-enrolled-p *rando*))
(ok "revoke on the owner's authority works"
    (and (search " ok " (raw (format nil "glass-admit/1 revoke pub=~a arg=all" *owner*)))
         (not (glass:device-enrolled-p *rando*))))
(ok "mint refuses a stranger" (search "deny" (raw (format nil "glass-admit/1 mint pub=~a" *guest*))))
(ok "and answers the owner with a token that verifies"
    (let* ((r (raw (format nil "glass-admit/1 mint pub=~a ttl=300" *owner*)))
           (at (search "token=" r)))
      (and at (glass:verify-login-token
               (subseq r (+ at 6) (or (position #\Space r :start at) (length r)))))))

;; PUB IS THE AUTHORITY, `for' IS THE RECIPIENT, and their difference is the difference between a
;; LINK and a TOP-UP.  The gateway sends `mint pub=X' with no `for' to top up an allowlist
;; admission; that must keep behaving exactly as it did, or one signature stops buying a durable
;; terminal.  A surface SENDING somebody a link says `for=' and gets superseding.
(flet ((tok (r) (let ((at (search "token=" r)))
                  (and at (subseq r (+ at 6) (or (position #\Space r :start at) (length r)))))))
  (let ((rcpt (hexkey #xC0DE01)))
    (let* ((a (tok (raw (format nil "glass-admit/1 mint pub=~a for=~a" *owner* rcpt))))
           (r2 (raw (format nil "glass-admit/1 mint pub=~a for=~a" *owner* rcpt)))
           (b (tok r2)))
      (ok "mint for= names a recipient and supersedes their earlier outstanding code"
          (and (search "superseded=1" r2)
               (eq :superseded (glass:code-state (glass:find-login-code
                                                  (nth-value 1 (glass:verify-login-token a))))))
          r2)
      (ok "  …and the newer one is the live one" (glass:verify-login-token b)))
    (let* ((r (raw (format nil "glass-admit/1 mint pub=~a" *owner*)))
           (top-up (tok r)))
      (ok "mint with NO for= is a TOP-UP: nothing is recorded, so it supersedes nothing"
          (and top-up (null (glass:find-login-code
                             (nth-value 1 (glass:verify-login-token top-up))))))
      (ok "  …and it carries the RENEWAL ttl, because it has to survive to the next cold load"
          (> (- (nth-value 2 (glass:verify-login-token top-up)) (glass:unix-now))
             glass:*login-ttl*)
          r))))

;;; ---- and the client half, which is what a gateway actually calls -------------

(format t "~&   -- the client end, the way a transport uses it --~%")
(defmacro at-service (&rest form) `(,@form :host "127.0.0.1" :port *port*))

(ok "PING reports the service's posture" (not (null (at-service glass:admission-ping))))
(let ((code (glass:mint-login-token :ttl 900)))
  (multiple-value-bind (via token) (at-service glass:admission-admit *guest* code)
    (ok "ADMISSION-ADMIT returns the way in as a keyword" (eq :code via))
    (ok "  …and a usable renewal token" (glass:verify-login-token token))))
(multiple-value-bind (via reason) (at-service glass:admission-admit *rando* nil)
  (ok "a refusal is NIL with a REASON, not an error" (and (null via) (eq :absent reason))))
(ok "ADMISSION-ALLOWED-P is the allowlist" (at-service glass:admission-allowed-p *owner*))
(ok "  …and says no for an enrolled device" (not (at-service glass:admission-allowed-p *guest*)))
(ok "ADMISSION-DEVICES returns the store as pairs"
    (let ((d (at-service glass:admission-devices)))
      (and (= 1 (length d)) (equal *guest* (car (first d))) (integerp (cdr (first d))))))
(ok "ADMISSION-MINT answers the owner" (not (null (at-service glass:admission-mint *owner*))))
(ok "ADMISSION-REVOKE refuses a stranger"
    (multiple-value-bind (r why) (at-service glass:admission-revoke *rando* "all")
      (and (null r) (eq :denied why))))
(ok "  …and obeys the owner"
    (and (at-service glass:admission-revoke *owner* "all")
         (null (at-service glass:admission-devices))))

;;; ---- THE CASE THE GATEWAY'S FAILURE POLICY IS BUILT ON -----------------------
;;; A desktop that is down must be distinguishable from a desktop that says no.  If these two
;;; arrived the same way, a gateway could not fail closed without also failing closed on every
;;; ordinary denial — and could not fail open without opening on a real one.

(format t "~&   -- with nothing listening: :UNREACHABLE, and never a plain denial --~%")
(glass:stop-admission-service *srv*)
(sleep 0.3)
(multiple-value-bind (via reason) (at-service glass:admission-admit *owner* nil)
  (ok "ADMIT: no service is (NIL :unreachable), which a denial never is"
      (and (null via) (eq :unreachable reason))))
(multiple-value-bind (allowed why) (at-service glass:admission-allowed-p *owner*)
  (ok "ALLOWED-P: NIL, and it says why — a caller that cannot ask must not promote anybody"
      (and (null allowed) (eq :unreachable why))))
(multiple-value-bind (rows why) (at-service glass:admission-devices)
  (ok "DEVICES: NIL :unreachable, and NOT an empty list — `none enrolled' is a different fact"
      (and (null rows) (eq :unreachable why))))
(ok "PING is simply NIL" (null (at-service glass:admission-ping)))
(ok "and none of it signalled" t)

;;; ==============================================================================
(banner "core glass still carries no crypto — checked in a CHILD, not by assertion here")
;;; ==============================================================================
;;;
;;; This image has cl-nostr and ironclad in it by definition: it just loaded :glass/nostr.  So the
;;; claim in glass.asd — "core :glass carries no crypto and no relay client" — cannot be checked
;;; from in here at all, and an assertion that pretended to would be checking nothing.  A separate
;;; SBCL loads plain :glass and reports what packages exist in it.

(defparameter *child-script* "/tmp/glass-nostr-gate-nocrypto.lisp")
(with-open-file (s *child-script* :direction :output :if-exists :supersede
                                  :if-does-not-exist :create)
  (write-string "(require :asdf)
(load \"~/quicklisp/setup.lisp\")
(push #p\"/home/claude/glass/\" asdf:*central-registry*)
(handler-bind ((warning #'muffle-warning))
  (let ((*standard-output* (make-broadcast-stream))) (asdf:load-system :glass)))
(format t \"~&VERDICT ~a ~a~%\"
        (if (find-package :ironclad) \"ironclad\" \"no-ironclad\")
        (if (find-package :cl-nostr.keys) \"cl-nostr\" \"no-cl-nostr\"))
(finish-output)
" s))
(let* ((out (make-string-output-stream))
       (proc (sb-ext:run-program "sbcl" (list "--non-interactive" "--disable-debugger"
                                              "--load" *child-script*)
                                 :output out :error out :search t))
       (said (get-output-stream-string out)))
  (ok "a child image that loads only :glass exits cleanly"
      (eql 0 (sb-ext:process-exit-code proc)))
  (ok "  …and has NO ironclad and NO cl-nostr in it — the optional system is really optional"
      (search "VERDICT no-ironclad no-cl-nostr" said)
      (string-trim '(#\Newline #\Space)
                   (or (let ((at (search "VERDICT" said)))
                         (and at (subseq said at (min (length said) (+ at 40)))))
                       said))))

;;; ==============================================================================
(banner "the live enrolment file was never opened")
;;; ==============================================================================

(ok "the live store's mtime is exactly what it was before this suite ran"
    (equal *live-mtime-before* (and (probe-file *live*) (file-write-date *live*)))
    (format nil "~a" *live-mtime-before*))
(ok "and no login-code store was created beside it either"
    (equal *live-codes-before* (and (probe-file *live-codes*) (file-write-date *live-codes*))))
;; THE ONE THAT MATTERS MOST.  ~/.glass-devices is the store the running desktop admits people from;
;; a suite that rewrote it would revoke somebody's terminal to pass, which has happened here before.
;; It is checked by NAME rather than by trusting that *ENROLMENT-FILE* was rebound early enough.
(let ((home-store (namestring (merge-pathnames ".glass-devices" (user-homedir-pathname)))))
  (ok "the DESKTOP's own store was never named by anything this suite ran"
      (and (not (equal glass:*enrolment-file* home-store))
           (not (equal (glass:login-code-file) (concatenate 'string home-store ".codes"))))
      home-store))
(ignore-errors (delete-file *fixture*))
(ignore-errors (delete-file (concatenate 'string *fixture* ".codes")))

(format t "~&~%~a passed, ~a failed~%" *pass* *fail*)
(finish-output)
(sb-ext:exit :code (if (zerop *fail*) 0 1))
