;;;; nostr-gate.lisp — the identity, the store, the commands, and the service on a real socket.
;;;;
;;;;   sbcl --non-interactive --load inspect/nostr-gate.lisp
;;;;
;;;; src/nostr.lisp moved the enrolment store, the token mint and the DM command surface out of a
;;;; WebRTC gateway and into the desktop.  Three claims come with that move and all three are
;;;; checkable without a relay, without a gateway and without a phone:
;;;;
;;;;   1. A TOKEN MINTED BY THE OLD IMPLEMENTATION STILL VERIFIES.  Every magic link in somebody's
;;;;      message history is a string in the old format keyed by the old MAC, so this is not a
;;;;      nicety — it is whether the day this deploys is the day every issued link stops working.
;;;;      The check is a LITERAL token, minted by demo/glass-webrtc/login-token.lisp against a
;;;;      literal secret, frozen here.  A literal rather than a call, so it survives that file
;;;;      being deleted and cannot be quietly regenerated by the thing it is testing.
;;;;
;;;;   2. `devices' AND `revoke' ARE ALLOWLIST-ONLY.  A device key is a bearer credential that can
;;;;      be lifted out of a browser; it may ask for a link and nothing else.  If it could revoke,
;;;;      one stolen browser key could lock the owner out of their own desktop, and if it could
;;;;      list, it could enumerate the fleet.  Both are asserted from the device's side.
;;;;
;;;;   3. THE SERVICE IS THE PROTOCOL, not a function call dressed up as one.  Everything below the
;;;;      "over a real socket" banner goes through TCP on loopback, parses the reply text, and
;;;;      exercises the case the gateway's failure policy is built on: a service that is NOT THERE
;;;;      must answer :UNREACHABLE and never NIL-that-looks-like-a-denial.
;;;;
;;;; NOTHING HERE READS OR WRITES THE LIVE ENROLMENT FILE.  A suite that pointed at it would revoke
;;;; a real terminal to pass, which has happened on this box before.  The fixture is in /tmp, it is
;;;; bound before anything is called, and there is an assertion that it is.

(require :asdf)
(load "~/quicklisp/setup.lisp")
(handler-bind ((warning #'muffle-warning))
  (let ((*standard-output* (make-broadcast-stream)))
    (asdf:load-system :glass/nostr)))

(defpackage #:glass-nostr-gate (:use #:cl)) (in-package #:glass-nostr-gate)

(defvar *pass* 0) (defvar *fail* 0)
(defun ok (name p &optional detail)
  (if p (progn (incf *pass*) (format t "  ok   ~a~@[ — ~a~]~%" name detail))
      (progn (incf *fail*) (format t "  FAIL ~a~@[ — ~a~]~%" name detail)))
  (finish-output))
(defun banner (s) (format t "~&~%== ~a ==~%" s))

;;; ---- the fixture, in /tmp, and never anywhere else ---------------------------

(defparameter *fixture* "/tmp/glass-nostr-gate-devices")
(defparameter *live* "/home/claude/webrtc-data/demo/glass-webrtc/.glass-devices")

(defparameter *owner* "1111111111111111111111111111111111111111111111111111111111111111")
(defparameter *guest* "2222222222222222222222222222222222222222222222222222222222222222")
(defparameter *rando* "3333333333333333333333333333333333333333333333333333333333333333")

(defparameter *secret* "00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff")

(ignore-errors (delete-file *fixture*))
(setf glass:*enrolment-file* *fixture*
      glass::*enrolments-mtime* nil
      glass:*box-secret* *secret*
      glass:*login-url-base* "https://example.invalid/k1.html")
(glass:refresh-nostr-allow *owner*)
(clrhash glass:*enrolments*)

(banner "the fixture is in /tmp and the live store is not touched")
(ok "the enrolment file is under /tmp" (eql 0 (search "/tmp/" glass:*enrolment-file*)))
(ok "and it is not the live one" (not (equal glass:*enrolment-file* *live*)))
(let ((before (and (probe-file *live*) (file-write-date *live*))))
  (defparameter *live-mtime-before* before)
  (ok "the live store's mtime is noted, and checked again at the end"
      (or (null before) (integerp before))))

;;; ==============================================================================
(banner "the identity")
;;; ==============================================================================

(ok "a 64-hex secret is an identity" (glass:box-identity-p))
(ok "and it has a pubkey" (let ((p (glass:box-pubkey))) (and (stringp p) (= 64 (length p)))))
(ok "and an npub, which is its public name"
    (let ((n (glass:box-npub))) (and (stringp n) (eql 0 (search "npub1" n)))))
(let ((glass:*box-secret* nil))
  (ok "no secret is no identity — and that is a refusal, not a fallback"
      (and (not (glass:box-identity-p)) (null (glass:box-pubkey))))
  (ok "…so nothing can be minted with it" (null (glass:mint-login-token))))
(let ((glass:*box-secret* "nope"))
  (ok "and neither is a short one" (not (glass:box-identity-p))))

;;; ==============================================================================
(banner "login tokens — the format is frozen, and this is the proof")
;;; ==============================================================================

;; MINTED BY THE PREVIOUS IMPLEMENTATION (demo/glass-webrtc/login-token.lisp, GLASS-LOGIN:%MAC)
;; against *SECRET*, with a nonce and an expiry chosen so the literal never goes stale:
;;     nonce 0123456789abcdef0123456789abcdef   exp 4102444800 (2100-01-01)
;; If this line ever has to be regenerated, every login link ever issued has already broken.
(defparameter *old-token*
  "0123456789abcdef0123456789abcdef.4102444800.733c4bc58fcd558359520d9e673f2d072755cdfeed281415016418bbbac44638")

(multiple-value-bind (ok-p nonce exp) (glass:verify-login-token *old-token*)
  (ok "a token minted by the OLD code verifies under the new one" ok-p)
  (ok "  …with the same nonce" (equal nonce "0123456789abcdef0123456789abcdef"))
  (ok "  …and the same expiry" (eql exp 4102444800)))
(ok "and it is :OK, not merely parseable" (eq :ok (glass:login-token-status *old-token*)))

(let ((fresh (glass:mint-login-token :ttl 900)))
  (ok "a freshly minted token verifies" (glass:verify-login-token fresh))
  (ok "it has the same three-field shape the browser and the link minter parse"
      (and (= 2 (count #\. fresh))
           (let* ((d1 (position #\. fresh)) (d2 (position #\. fresh :from-end t)))
             (and (= 32 d1) (parse-integer (subseq fresh (1+ d1) d2))
                  (= 64 (- (length fresh) d2 1))))))
  (ok "two mints differ — the nonce is random, so a link is not a constant"
      (not (equal fresh (glass:mint-login-token :ttl 900))))
  (ok "a token from another box's secret does NOT verify here"
      (not (glass:verify-login-token
            (glass:mint-login-token :ttl 900 :secret (make-string 64 :initial-element #\a)))))
  (ok "a flipped MAC character is refused"
      (let ((bad (copy-seq fresh)))
        (setf (char bad (1- (length bad))) (if (char= #\a (char bad (1- (length bad)))) #\b #\a))
        (not (glass:verify-login-token bad))))
  (ok "and garbage is :BAD rather than an error" (eq :bad (glass:login-token-status "not-a-token")))
  (ok "an absent code is :ABSENT, which is a different denial"
      (and (eq :absent (glass:login-token-status nil))
           (eq :absent (glass:login-token-status "")))))

;; expiry is checked, and reported as its own reason so a denial is diagnosable
(let ((expired (let ((n "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") (e (- (glass:unix-now) 60)))
                 (format nil "~a.~a.~a" n e (glass::%token-mac *secret* n e)))))
  (ok "a good MAC on a past expiry is :EXPIRED, not :BAD"
      (eq :expired (glass:login-token-status expired)))
  (ok "  …and VERIFY still hands back the nonce, which is what tells the two apart"
      (multiple-value-bind (ok-p nonce) (glass:verify-login-token expired)
        (and (null ok-p) (equal nonce "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")))))

;;; ==============================================================================
(banner "the allowlist")
;;; ==============================================================================

(ok "the owner is allowed" (glass:allowed-pubkey-p *owner*))
(ok "a guest is not" (not (glass:allowed-pubkey-p *guest*)))
(ok "case does not matter — pubkeys arrive in whatever case they were written in"
    (glass:allowed-pubkey-p (string-upcase *owner*)))
(let ((glass:*nostr-allow* '()))
  (ok "AN EMPTY ALLOWLIST DENIES EVERYONE — with nobody to authorise there is no one to say yes to"
      (and (not (glass:allowed-pubkey-p *owner*)) (not (glass:allowed-pubkey-p *guest*)))))
(ok "NIL is not a pubkey" (not (glass:allowed-pubkey-p nil)))
(ok "the allowlist can be re-read at run time, which the gateway's could not"
    (let ((glass:*nostr-allow* nil))
      (glass:refresh-nostr-allow (format nil "~a,~a" *owner* *guest*))
      (prog1 (and (glass:allowed-pubkey-p *owner*) (glass:allowed-pubkey-p *guest*))
        (glass:refresh-nostr-allow *owner*))))

;;; ==============================================================================
(banner "the enrolment store")
;;; ==============================================================================

(ok "nothing is enrolled to start with" (null (glass:list-enrolments)))
(ok "a guest is not enrolled" (not (glass:device-enrolled-p *guest*)))
(glass:enrol-device *guest*)
(ok "enrolling one makes it enrolled" (glass:device-enrolled-p *guest*))
(ok "and it is persisted — the FILE is the source of truth, not this process's memory"
    (with-open-file (s *fixture*) (search *guest* (or (read-line s nil "") ""))))
(glass:enrol-device *rando*)
(ok "two terminals, listed longest-remaining first" (= 2 (glass:enrolment-count)))

;; the mechanism the whole store was designed around: another process writes, we honour it
(let ((now (glass:unix-now)))
  (sleep 1.1)                              ; file-write-date has one-second resolution
  (with-open-file (s *fixture* :direction :output :if-exists :supersede)
    (format s "~a ~a~%" *guest* (+ now 86400)))
  (ok "a revoke performed by ANOTHER process is honoured with no restart"
      (and (glass:device-enrolled-p *guest*) (not (glass:device-enrolled-p *rando*)))))

(glass:enrol-device *rando*)
(ok "a lapsed enrolment is not an enrolment"
    (progn (glass:enrol-device *rando* -10) (not (glass:device-enrolled-p *rando*))))
(glass:enrol-device *rando*)

(ok "revoke by 8-char prefix drops exactly one"
    (and (equal (list *rando*) (glass:revoke-enrolments (subseq *rando* 0 8)))
         (not (glass:device-enrolled-p *rando*))
         (glass:device-enrolled-p *guest*)))
(glass:enrol-device *rando*)
(ok "revoke all drops everything" (and (= 2 (length (glass:revoke-enrolments "all")))
                                       (null (glass:list-enrolments))))
(ok "a prefix that matches nothing revokes nothing" (null (glass:revoke-enrolments "deadbeef")))
(ok "a prefix shorter than four characters is refused rather than matching half the fleet"
    (progn (glass:enrol-device *guest*)
           (and (null (glass:revoke-enrolments "22")) (glass:device-enrolled-p *guest*))))

;;; ==============================================================================
(banner "admission — three ways in, first match wins")
;;; ==============================================================================

(glass:revoke-enrolments "all")
(let ((code (glass:mint-login-token :ttl 900)))
  (multiple-value-bind (via token status) (glass:admit-peer *rando* code)
    (ok "a valid code admits a stranger — that is what a magic link is for" (eq :code via))
    (ok "  …and it is reported as :OK" (eq :ok status))
    (ok "  …and a renewal token rides back, so reconnecting never needs a new link"
        (and token (glass:verify-login-token token)))
    (ok "  …and the caller is now an enrolled terminal" (glass:device-enrolled-p *rando*))))

(multiple-value-bind (via token status) (glass:admit-peer *rando* nil)
  (ok "the enrolled terminal gets back in with no code at all" (eq :device via))
  (ok "  …still with a renewal" (not (null token)))
  (ok "  …and the missing code is reported as :ABSENT, not as a bad one" (eq :absent status)))

(multiple-value-bind (via token) (glass:admit-peer *owner* nil)
  (ok "the owner is admitted by the allowlist" (eq :allowlist via))
  (ok "and is handed NO bearer credential — an owner has a signer and does not need one"
      (null token)))

(multiple-value-bind (via nil* status) (glass:admit-peer *guest* "garbage")
  (declare (ignore nil*))
  (ok "a stranger with a bad code is refused" (null via))
  (ok "  …and the reason says WHY, so a locked-out person is diagnosable" (eq :bad status)))

(ok "a refused peer is NOT enrolled — a denial that enrolled would be the bug that matters"
    (not (glass:device-enrolled-p *guest*)))

;; The owner is by now an ENROLLED terminal too — ADMIT-PEER enrols everyone it admits — so the
;; peer used here has to be one that has never been let in, or this would be checking the device
;; path while claiming to check the allowlist one.
(let ((glass:*nostr-allow* '())
      (never "4444444444444444444444444444444444444444444444444444444444444444"))
  (ok "with no allowlist, no enrolment and no code, nobody is admitted"
      (and (null (glass:admit-peer never nil))
           (not (glass:device-enrolled-p never)))))

;;; ==============================================================================
(banner "the command surface — and who may run each command")
;;; ==============================================================================

(glass:revoke-enrolments "all")
(glass:enrol-device *guest*)                       ; a device key, the bearer credential
;; *rando* is neither on the allowlist nor enrolled

(flet ((verb (s) (nth-value 0 (glass:parse-nostr-command s)))
       (arg (s) (nth-value 1 (glass:parse-nostr-command s))))
  (ok "link / devices / revoke / help are the four verbs"
      (equal '(:link :devices :revoke :help)
             (list (verb "link") (verb "devices") (verb "revoke abc12345") (verb "help"))))
  (ok "? is help" (eq :help (verb "?")))
  (ok "revoke carries its argument" (equal "abc12345" (arg "revoke abc12345")))
  (ok "case and surrounding space do not matter" (eq :link (verb "  LINK  ")))
  (ok "an SDP offer is not a command — which is what keeps this bot off the gateway's traffic"
      (null (verb (format nil "v=0~%o=- 1 1 IN IP4 0.0.0.0~%m=application 9 UDP/DTLS/SCTP webrtc-datachannel~a"
                          (make-string 200 :initial-element #\x)))))
  (ok "and neither is chatter" (null (verb "how are you")))
  (ok "`link' is matched as a substring, so `blink' mints one too — kept, and documented"
      (eq :link (verb "blink"))))

(flet ((reply (pub text) (nth-value 0 (glass:nostr-command-reply pub text)))
       (role (pub text) (nth-value 2 (glass:nostr-command-reply pub text))))
  (format t "~&   -- the owner (allowlisted) --~%")
  (ok "owner: link -> a magic link with the box npub and a live code in the fragment"
      (let ((r (reply *owner* "link")))
        (and (stringp r) (search "#box=npub1" r) (search "&code=" r))))
  (ok "  …and the code in it verifies"
      (let* ((r (reply *owner* "link")) (at (search "&code=" r)))
        (glass:verify-login-token (subseq r (+ at 6)))))
  (ok "owner: devices -> the list" (search "enrolled terminal" (reply *owner* "devices")))
  (ok "owner: help -> mentions the management commands it may use"
      (let ((r (reply *owner* "help"))) (and (search "devices" r) (search "revoke" r))))
  (ok "owner is classified :allowlist" (eq :allowlist (role *owner* "help")))

  (format t "~&   -- an enrolled DEVICE: a bearer credential, and bounded like one --~%")
  (ok "device: link -> allowed.  A terminal whose code lapses can refresh itself"
      (stringp (reply *guest* "link")))
  (ok "device: devices -> DENIED.  A stolen browser key must not enumerate the fleet"
      (eq :denied (reply *guest* "devices")))
  (ok "device: revoke -> DENIED.  It must not revoke the others, or itself into permanence"
      (eq :denied (reply *guest* "revoke all")))
  (ok "  …and the enrolments it tried to revoke are all still there"
      (glass:device-enrolled-p *guest*))
  (ok "device: help -> allowed, and does NOT advertise commands it may not run"
      (let ((r (reply *guest* "help")))
        (and (stringp r) (search "link" r) (not (search "revoke" r)))))
  (ok "device is classified :device" (eq :device (role *guest* "help")))

  (format t "~&   -- a stranger: no reply at all, which is the denial --~%")
  (ok "stranger: link -> denied" (eq :denied (reply *rando* "link")))
  (ok "stranger: devices -> denied" (eq :denied (reply *rando* "devices")))
  (ok "stranger: revoke -> denied" (eq :denied (reply *rando* "revoke all")))
  (ok "stranger: help -> denied.  Even the usage is an oracle that the box is listening"
      (eq :denied (reply *rando* "help")))
  (ok "a stranger has no role" (null (role *rando* "help")))
  (ok "and a non-command is NIL rather than :denied — there is nothing to deny"
      (null (reply *rando* "hello there"))))

(ok "the owner's revoke actually revokes"
    (progn (glass:nostr-command-reply *owner* (format nil "revoke ~a" (subseq *guest* 0 8)))
           (not (glass:device-enrolled-p *guest*))))

;;; ==============================================================================
(banner "the service, over a real loopback socket")
;;; ==============================================================================

(defparameter *port* 15915)     ; not 5915: a gate must never race the desktop's own service

;; the raw wire, spoken by hand: `nc localhost 5915' has to be a diagnostic, so the bytes are
;; asserted rather than only the client library that writes them
(defun raw (line &key (expect-rows 0))
  (let ((sock (make-instance 'sb-bsd-sockets:inet-socket :type :stream :protocol :tcp)))
    (unwind-protect
         (progn
           (sb-bsd-sockets:socket-connect
            sock (sb-bsd-sockets:make-inet-address "127.0.0.1") *port*)
           (let ((s (sb-bsd-sockets:socket-make-stream sock :input t :output t
                                                            :element-type 'character
                                                            :buffering :full :timeout 5)))
             (write-string line s) (write-char #\Newline s) (force-output s)
             (let ((head (read-line s nil "")))
               (values head (loop repeat expect-rows collect (read-line s nil ""))))))
      (ignore-errors (sb-bsd-sockets:socket-close sock)))))

(glass:revoke-enrolments "all")
(defparameter *srv* (glass:start-admission-service :port *port* :install nil))
(ok "the service is listening" (not (null *srv*)))
(sleep 0.2)

(ok "ping answers with the box's posture, in one readable line"
    (let ((r (raw "glass-admit/1 ping")))
      (format t "     ~a~%" r)
      (and (eql 0 (search "glass-admit/1 ok " r))
           (search (format nil "box=~a" (glass:box-pubkey)) r)
           (search "allow=1" r))))
(ok "an unknown verb is an error and not a crash"
    (search "err reason=unknown-op" (raw "glass-admit/1 fly-me-to-the-moon")))
(ok "and so is junk on the wire" (search "err" (raw "hello")))

(let ((code (glass:mint-login-token :ttl 900)))
  (ok "admit with a good code says ok, names the way in, and hands back a renewal"
      (let ((r (raw (format nil "glass-admit/1 admit pub=~a code=~a" *rando* code))))
        (format t "     ~a~%" r)
        (and (search " ok " r) (search "via=code" r) (search "token=" r))))
  (ok "  …and the peer is now enrolled, on this desktop's side of the wire"
      (glass:device-enrolled-p *rando*)))
(ok "admit with no code and no standing is DENIED, with the reason"
    (let ((r (raw (format nil "glass-admit/1 admit pub=~a" *guest*))))
      (and (search " deny " r) (search "reason=absent" r))))
(ok "admit with a rotten code says so specifically"
    (search "reason=bad" (raw (format nil "glass-admit/1 admit pub=~a code=zzz" *guest*))))
(ok "allowed is the allowlist and nothing else"
    (and (search "allowed=1" (raw (format nil "glass-admit/1 allowed pub=~a" *owner*)))
         (search "allowed=0" (raw (format nil "glass-admit/1 allowed pub=~a" *rando*)))))
(ok "  …and an enrolled DEVICE is still not allowlisted, which is the whole distinction"
    (and (glass:device-enrolled-p *rando*)
         (search "allowed=0" (raw (format nil "glass-admit/1 allowed pub=~a" *rando*)))))

(multiple-value-bind (head rows) (raw "glass-admit/1 devices" :expect-rows 1)
  (ok "devices answers rows=N then N lines of `<pubkey> <expiry>'"
      (and (search "rows=1" head)
           (eql 0 (search *rando* (first rows)))
           (parse-integer (subseq (first rows) 65) :junk-allowed t))))

(ok "revoke on a stranger's authority is DENIED — the rule is enforced here, not at the surface"
    (search "deny reason=not-allowed"
            (raw (format nil "glass-admit/1 revoke pub=~a arg=all" *guest*))))
(ok "  …and nothing was revoked" (glass:device-enrolled-p *rando*))
(ok "revoke on the owner's authority works"
    (and (search " ok " (raw (format nil "glass-admit/1 revoke pub=~a arg=all" *owner*)))
         (not (glass:device-enrolled-p *rando*))))
(ok "mint refuses a stranger" (search "deny" (raw (format nil "glass-admit/1 mint pub=~a" *guest*))))
(ok "and answers the owner with a token that verifies"
    (let* ((r (raw (format nil "glass-admit/1 mint pub=~a ttl=300" *owner*)))
           (at (search "token=" r)))
      (and at (glass:verify-login-token
               (subseq r (+ at 6) (or (position #\Space r :start at) (length r)))))))

;;; ---- and the client half, which is what a gateway actually calls -------------

(format t "~&   -- the client end, the way a transport uses it --~%")
(defmacro at-service (&rest form) `(,@form :host "127.0.0.1" :port *port*))

(ok "PING reports the service's posture" (not (null (at-service glass:admission-ping))))
(let ((code (glass:mint-login-token :ttl 900)))
  (multiple-value-bind (via token) (at-service glass:admission-admit *guest* code)
    (ok "ADMISSION-ADMIT returns the way in as a keyword" (eq :code via))
    (ok "  …and a usable renewal token" (glass:verify-login-token token))))
(multiple-value-bind (via reason) (at-service glass:admission-admit *rando* nil)
  (ok "a refusal is NIL with a REASON, not an error" (and (null via) (eq :absent reason))))
(ok "ADMISSION-ALLOWED-P is the allowlist" (at-service glass:admission-allowed-p *owner*))
(ok "  …and says no for an enrolled device" (not (at-service glass:admission-allowed-p *guest*)))
(ok "ADMISSION-DEVICES returns the store as pairs"
    (let ((d (at-service glass:admission-devices)))
      (and (= 1 (length d)) (equal *guest* (car (first d))) (integerp (cdr (first d))))))
(ok "ADMISSION-MINT answers the owner" (not (null (at-service glass:admission-mint *owner*))))
(ok "ADMISSION-REVOKE refuses a stranger"
    (multiple-value-bind (r why) (at-service glass:admission-revoke *rando* "all")
      (and (null r) (eq :denied why))))
(ok "  …and obeys the owner"
    (and (at-service glass:admission-revoke *owner* "all")
         (null (at-service glass:admission-devices))))

;;; ---- THE CASE THE GATEWAY'S FAILURE POLICY IS BUILT ON -----------------------
;;; A desktop that is down must be distinguishable from a desktop that says no.  If these two
;;; arrived the same way, a gateway could not fail closed without also failing closed on every
;;; ordinary denial — and could not fail open without opening on a real one.

(format t "~&   -- with nothing listening: :UNREACHABLE, and never a plain denial --~%")
(glass:stop-admission-service *srv*)
(sleep 0.3)
(multiple-value-bind (via reason) (at-service glass:admission-admit *owner* nil)
  (ok "ADMIT: no service is (NIL :unreachable), which a denial never is"
      (and (null via) (eq :unreachable reason))))
(multiple-value-bind (allowed why) (at-service glass:admission-allowed-p *owner*)
  (ok "ALLOWED-P: NIL, and it says why — a caller that cannot ask must not promote anybody"
      (and (null allowed) (eq :unreachable why))))
(multiple-value-bind (rows why) (at-service glass:admission-devices)
  (ok "DEVICES: NIL :unreachable, and NOT an empty list — `none enrolled' is a different fact"
      (and (null rows) (eq :unreachable why))))
(ok "PING is simply NIL" (null (at-service glass:admission-ping)))
(ok "and none of it signalled" t)

;;; ==============================================================================
(banner "the live enrolment file was never opened")
;;; ==============================================================================

(ok "the live store's mtime is exactly what it was before this suite ran"
    (equal *live-mtime-before* (and (probe-file *live*) (file-write-date *live*)))
    (format nil "~a" *live-mtime-before*))
(ignore-errors (delete-file *fixture*))

(format t "~&~%~a passed, ~a failed~%" *pass* *fail*)
(finish-output)
(sb-ext:exit :code (if (zerop *fail*) 0 1))
